const { onCall, HttpsError } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
const db={collection:(...a)=>admin.firestore().collection(...a),runTransaction:(...a)=>admin.firestore().runTransaction(...a)};
const PAY_FREQUENCIES=['monthly','weekly','daily','hourly']; const RECURRENCE_TYPES=['recurring','oneTime','one-time']; const OT_MULTIPLIERS={normal:1.5,restDay:2,publicHoliday:3}; const OT_VERSION='v1'; const MAX_HOURS=24; const MAX_OT_HOURS=16;
function requireAuth(r){const uid=r.auth?.uid;if(!uid)throw new HttpsError('unauthenticated','You must be signed in.');return uid;}
async function actor(uid){const s=await db.collection('users').doc(uid).get();if(!s.exists)throw new HttpsError('not-found','Account not found.');return s.data()||{};}
function assertOwnerOrAdmin(uid,target,p){if(uid!==target&&!['admin','superadmin'].includes(p.role))throw new HttpsError('permission-denied','You can only change your own salary records.');}
function cleanText(v,max=120){const t=String(v??'').trim();if(t.length>max)throw new HttpsError('invalid-argument','Text value is too long.');return t;}
function money(v,f){const n=Number(v);if(!Number.isFinite(n)||n<0||n>100000000||Math.round(n*100)!==n*100)throw new HttpsError('invalid-argument',`Invalid ${f}.`);return Math.round(n*100)/100;}
function hours(v,f){const n=Number(v);if(!Number.isFinite(n)||n<0||n>MAX_HOURS||Math.round(n*100)!==n*100)throw new HttpsError('invalid-argument',`Invalid ${f}.`);return Math.round(n*100)/100;}
function recordId(v){const id=String(v||'');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(id))throw new HttpsError('invalid-argument','Invalid salary record month.');return id;}
function round2(v){return Math.round((Number(v)||0)*100)/100;}
function normalizeOtMethod(v){return v==='custom'||v==='custom_employer_rate'?'custom_employer_rate':'mysheba_default';}
function calculateBasicPay(basic,days,worked){const s=Number(basic)||0,d=Number(days)||0,w=Number(worked)||0;return d>0?round2(s/d*w):0;}
function deriveHourlyRate(basic,hpd,dpw){const s=Number(basic)||0,h=Number(hpd)||0,d=Number(dpw)||0;const mh=h*d*(52/12);return mh>0?round2(s/mh):0;}
function calculateOtForPeriod(entries,method,hourlyRate,custom){const norm=normalizeOtMethod(method);return(entries||[]).reduce((t,e)=>{const oh=Number(e.otHours)||0;if(oh<=0)return t;const rate=norm==='custom_employer_rate'?Number(custom)||0:hourlyRate*(OT_MULTIPLIERS[e.otType]??1.5);t.otPay=round2(t.otPay+oh*rate);t.otHours=round2(t.otHours+oh);return t;},{otPay:0,otHours:0});}
async function getMonthlyCalculation(targetUid,year,month){const base=db.collection('users').doc(targetUid);const ss=await base.collection('salarySettings').doc('current').get();if(!ss.exists)throw new HttpsError('failed-precondition','Salary settings are not configured yet.');const settings=ss.data()||{};const start=`${year}-${String(month).padStart(2,'0')}-01`,last=new Date(Date.UTC(year,month,0)).getUTCDate(),end=`${year}-${String(month).padStart(2,'0')}-${String(last).padStart(2,'0')}`;const ws=await base.collection('workLogs').get();const entries=ws.docs.filter(d=>d.id>=start&&d.id<=end).map(d=>({id:d.id,...d.data()}));const daysWorked=entries.filter(e=>e.status==='worked').length;const workingDaysInMonth=Math.round((Number(settings.workingDaysPerWeek)||6)*(52/12));const hourlyRate=deriveHourlyRate(settings.basicSalary,settings.normalHoursPerDay,settings.workingDaysPerWeek);const ot=calculateOtForPeriod(entries,settings.otCalculationMethod,hourlyRate,settings.customOtRate);const [as,ds]=await Promise.all([base.collection('allowances').get(),base.collection('deductions').get()]);const allowances=round2(as.docs.reduce((s,d)=>{const x=d.data()||{};return RECURRENCE_TYPES.includes(x.recurrence)&&x.recurrence!=='one-time'?s+(Number(x.amount)||0):s;},0));const deductions=round2(ds.docs.reduce((s,d)=>{const x=d.data()||{};return RECURRENCE_TYPES.includes(x.recurrence)&&x.recurrence!=='one-time'?s+(Number(x.amount)||0):s;},0));const basicPay=calculateBasicPay(settings.basicSalary,workingDaysInMonth,daysWorked),estimatedGross=round2(basicPay+ot.otPay+allowances);return{year,month,daysWorked,otHours:ot.otHours,basicPay,otPay:ot.otPay,allowances,deductions,estimatedGross,estimatedTakeHome:round2(estimatedGross-deductions),otCalculationMethod:normalizeOtMethod(settings.otCalculationMethod),otCalculationVersion:OT_VERSION,hourlyRate};}
exports.saveSalarySettings=onCall({enforceAppCheck:true},async r=>{const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);const s=r.data?.settings||{},data={basicSalary:money(s.basicSalary,'basic salary'),payFrequency:PAY_FREQUENCIES.includes(s.payFrequency)?s.payFrequency:'monthly',normalHoursPerDay:hours(s.normalHoursPerDay??8,'normal hours per day'),workingDaysPerWeek:hours(s.workingDaysPerWeek??6,'working days per week'),restDay:s.restDay==null?null:cleanText(s.restDay,20),employmentType:s.employmentType==null?null:cleanText(s.employmentType,40),currency:cleanText(s.currency||'RM',8),country:cleanText(s.country||'Malaysia',60),otCalculationMethod:normalizeOtMethod(s.otCalculationMethod),customOtRate:s.customOtRate==null?null:money(s.customOtRate,'custom OT rate'),remindersEnabled:s.remindersEnabled!==false,updatedAt:admin.firestore.FieldValue.serverTimestamp()},ref=db.collection('users').doc(target).collection('salarySettings').doc('current');await db.runTransaction(async tx=>{const s=await tx.get(ref);tx.set(ref,{...data,createdAt:s.exists&&s.data().createdAt?s.data().createdAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});});return{ok:true};});
async function mutateLineItem(r,kind){const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);const item=r.data?.item||{},name=cleanText(item.name,100);if(!name)throw new HttpsError('invalid-argument',`${kind} name is required.`);const amount=money(item.amount,`${kind} amount`),recurrence=RECURRENCE_TYPES.includes(item.recurrence)?item.recurrence:'recurring',col=db.collection('users').doc(target).collection(kind==='allowance'?'allowances':'deductions'),id=item.id?cleanText(item.id,128):null,ref=id?col.doc(id):col.doc(),data={name,amount,recurrence,updatedAt:admin.firestore.FieldValue.serverTimestamp()};if(!id)data.createdAt=admin.firestore.FieldValue.serverTimestamp();await ref.set(data,{merge:true});return{id:ref.id};}
exports.addAllowance=onCall({enforceAppCheck:true},r=>mutateLineItem(r,'allowance'));exports.updateAllowance=onCall({enforceAppCheck:true},r=>mutateLineItem(r,'allowance'));exports.addDeduction=onCall({enforceAppCheck:true},r=>mutateLineItem(r,'deduction'));exports.updateDeduction=onCall({enforceAppCheck:true},r=>mutateLineItem(r,'deduction'));
async function deleteLineItem(r,kind){const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);const id=cleanText(r.data?.id,128);if(!id)throw new HttpsError('invalid-argument','Item ID is required.');await db.collection('users').doc(target).collection(kind==='allowance'?'allowances':'deductions').doc(id).delete();return{ok:true};}
exports.deleteAllowance=onCall({enforceAppCheck:true},r=>deleteLineItem(r,'allowance'));exports.deleteDeduction=onCall({enforceAppCheck:true},r=>deleteLineItem(r,'deduction'));
exports.saveSalaryEstimate=onCall({enforceAppCheck:true},async r=>{const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);const id=recordId(r.data?.recordId),parts=id.split('-'),year=Number(parts[0]),month=Number(parts[1]),calculated=await getMonthlyCalculation(target,year,month),ref=db.collection('users').doc(target).collection('salaryRecords').doc(id);await db.runTransaction(async tx=>{const s=await tx.get(ref),d=s.exists?s.data():{};tx.set(ref,{...calculated,createdAt:d.createdAt||admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});});return{ok:true,calculation:calculated};});
exports.recordActualSalary=onCall({enforceAppCheck:true},async r=>{const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);const id=recordId(r.data?.recordId),actual=money(r.data?.actualSalaryReceived,'actual salary'),ref=db.collection('users').doc(target).collection('salaryRecords').doc(id);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Salary record not found. Save the monthly estimate first.');const d=s.data()||{};tx.update(ref,{actualSalaryReceived:actual,difference:round2(actual-(Number(d.estimatedTakeHome)||0)),updatedAt:admin.firestore.FieldValue.serverTimestamp()});});return{ok:true};});
exports.attachSalaryPayslip=onCall({enforceAppCheck:true},async r=>{const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);const id=recordId(r.data?.recordId),fileReference=cleanText(r.data?.fileReference,500);if(!fileReference)throw new HttpsError('invalid-argument','Payslip file reference is required.');const ref=db.collection('users').doc(target).collection('salaryRecords').doc(id);await ref.set({payslipFileReference:fileReference,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return{ok:true};});
exports.deleteSalaryRecord=onCall({enforceAppCheck:true},async r=>{const uid=requireAuth(r),p=await actor(uid),target=String(r.data?.userId||uid);assertOwnerOrAdmin(uid,target,p);await db.collection('users').doc(target).collection('salaryRecords').doc(recordId(r.data?.recordId)).delete();return{ok:true};});
