const { onCall, HttpsError } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
const crypto = require('crypto');
const progressionService = require('./progressionService');
const { logAudit, logServerError } = require('./logService');
const { checkVelocity, getClientIp } = require('./rateLimitService');
const { checkIpAnomaly } = require('./anomalyService');

const DEFAULT_PRICING={dealerEarningPercent:1.5,webviewAccessCost:2,webviewSubmitCost:2,paymentSuccessCost:3,webviewAccessWindowHours:1,notepadCost:0,myDocumentsCost:0,salaryOtCost:0,moduleSubscriptionDays:30};
const DEFAULT_RATES={mobileBanking:110.5,BD_ACC:30.26,BD_CASH:30.11,NP:37.65,PK:67.79,PH:15.05,LK:81.99,IN:23.5,ID:230,MM:966,remittanceFee:7,rechargeBD:30.26,rechargeIN:23.5,rechargeNP:37.65,rechargeID:230,rechargePK:67.79,rechargeMM:966,rechargePH:15.05,rechargeKH:900};
const RECHARGE_RATE_KEYS={BD:'rechargeBD',IN:'rechargeIN',NP:'rechargeNP',ID:'rechargeID',PK:'rechargePK',MM:'rechargeMM',PH:'rechargePH',KH:'rechargeKH'};
const SESSION_ID_RE=/^[A-Za-z0-9_-]{16,128}$/;
const DEVICE_ID_RE=/^[A-Za-z0-9-]{16,100}$/;
function requireSessionMatch(request,user){const sessionId=request.data?.sessionId,deviceId=request.data?.deviceId;if(typeof sessionId!=='string'||!SESSION_ID_RE.test(sessionId)||typeof deviceId!=='string'||!DEVICE_ID_RE.test(deviceId))throw new HttpsError('failed-precondition','Your secure session is missing. Please sign in again.');if(user.activeSessionId!==sessionId||user.activeDeviceId!==deviceId)throw new HttpsError('permission-denied','This device session is no longer active. Please sign in again.');}
async function getPricing(db){const s=await db.collection('settings').doc('pricing').get();return{...DEFAULT_PRICING,...(s.exists?s.data():{})};}
async function getRates(db){const s=await db.collection('rates').doc('current').get();return{...DEFAULT_RATES,...(s.exists?s.data():{})};}
async function getProfile(db,uid){const s=await db.collection('users').doc(uid).get();return s.exists?{id:s.id,...s.data()}:null;}
function requireAuth(r){if(!r.auth)throw new HttpsError('unauthenticated','You must be signed in.');return r.auth.uid;}
function priceForRole(p,key,role){const v=role&&p.rolePricing&&p.rolePricing[role]&&p.rolePricing[role][key];return v!=null?v:p[key];}
function amountToPoints(n,c,r){const x=Number(n)||0;const country=String(c||'').trim().toUpperCase();if(country==='MY')return{x,rate:1};const k=RECHARGE_RATE_KEYS[country];if(!k)throw new HttpsError('invalid-argument','Unsupported recharge country.');const rate=Number(r[k]);if(!Number.isFinite(rate)||rate<=0)throw new HttpsError('failed-precondition','The exchange rate for this country is unavailable.');return{x:Math.round(x/rate*100)/100,rate};}
function recompute(service,raw,rates){const r=raw||{};if(service==='recharge'||service==='internet'){const country=String(r.country||'').trim().toUpperCase();if(!country)throw new HttpsError('invalid-argument','Recharge country is required.');const q=amountToPoints(r.amount,country,rates);return{amount:q.x,total:q.x,exchangeRate:country!=='MY'?q.rate:null,exchangeRateSource:country!=='MY'?RECHARGE_RATE_KEYS[country]:null};}if(service==='mobilebanking'){const a=Math.round((Number(r.myr)||0)*100)/100;return{amount:a,total:Math.round((a+5)*100)/100,exchangeRate:Number(rates.mobileBanking)||110.5,exchangeRateSource:'mobileBanking'};}if(service==='billpayment'){const country=String(r.country||'').trim().toUpperCase();if(!['MY','BD'].includes(country))throw new HttpsError('invalid-argument','Unsupported bill payment country.');const raw=Math.round((Number(r.amount)||0)*100)/100;if(!Number.isFinite(raw)||raw<=0)throw new HttpsError('invalid-argument','Bill amount must be greater than zero.');const q=amountToPoints(raw,country,rates);return{amount:q.x,total:q.x,exchangeRate:q.rate,exchangeRateSource:country==='MY'?'MYR':RECHARGE_RATE_KEYS[country]};}if(service==='remittance'){const country=String(r.country||'').trim().toUpperCase();const allowed=['BD','NP','PK','PH','IN','ID','MM'];if(!allowed.includes(country))throw new HttpsError('invalid-argument','Unsupported remittance country.');const a=Math.round((Number(r.sendAmt)||0)*100)/100;const fee=Math.round((Number(rates.remittanceFee)||7)*100)/100;const rate=country==='BD'?(r.method==='deposit'?Number(rates.BD_ACC):Number(rates.BD_CASH)):Number(rates[country]);if(!Number.isFinite(rate)||rate<=0)throw new HttpsError('failed-precondition','The exchange rate for this country is unavailable.');return{amount:a,total:Math.round((a+fee)*100)/100,exchangeRate:rate,exchangeRateSource:country==='BD'?(r.method==='deposit'?'BD_ACC':'BD_CASH'):country};}return{amount:Number(r.amount)||0,total:Number(r.total)||0,exchangeRate:null,exchangeRateSource:null};}
function active(account){return !!account&&account.suspended!==true&&account.inactive!==true&&account.disabled!==true&&account.active!==false&&account.mergedInto==null;}

exports.approveTopup=onCall({ enforceAppCheck: true },async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!caller||!['admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Only an admin can approve top-ups.');const{id}=r.data||{};const topupId=id||r.data?.topupId;if(!topupId)throw new HttpsError('invalid-argument','topupId is required.');const ref=db.collection('topups').doc(topupId);try{const out=await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','That top-up request does not exist.');const t=s.data();if(t.status!=='pending')throw new HttpsError('failed-precondition','That request has already been reviewed.');const uref=db.collection('users').doc(t.userId),u=await tx.get(uref);if(!u.exists)throw new HttpsError('not-found','That user account no longer exists.');const user=u.data();if(!active(user))throw new HttpsError('failed-precondition','The recipient account is not active.');const pts=Number(t.points||t.amount||0),bal=Number(user.walletBalance||0);if(!Number.isFinite(pts)||pts<=0||!Number.isFinite(bal)||bal<0)throw new HttpsError('invalid-argument','Invalid wallet amount.');const next=bal+pts;if(!Number.isSafeInteger(Math.round(next*100)))throw new HttpsError('failed-precondition','Wallet balance is invalid.');tx.update(uref,{walletBalance:next});tx.update(ref,{status:'approved',approvedBy:uid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{userId:t.userId,points:pts};});await logAudit({action:'topup_approved',targetUid:out.userId,performedBy:uid,performedByRole:caller.role,details:{topupId,points:out.points}});return{approved:true};}catch(e){if(e instanceof HttpsError)throw e;await logServerError('approveTopup',e,{userId:uid});throw new HttpsError('internal','Could not approve this top-up.');}});
exports.rejectTopup=onCall({ enforceAppCheck: true },async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!caller||!['admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Only an admin can reject top-ups.');const{topupId,reason}=r.data||{};if(!topupId)throw new HttpsError('invalid-argument','topupId is required.');const ref=db.collection('topups').doc(topupId);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','That top-up request does not exist.');if(s.data().status!=='pending')throw new HttpsError('failed-precondition','That request has already been reviewed.');await ref.update({status:'rejected',rejectReason:typeof reason==='string'?reason.trim().slice(0,500):'',approvedBy:uid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{rejected:true};});
exports.createSelfTopup=onCall({ enforceAppCheck: true },async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!active(caller)||!['admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Only admin/superadmin can self-top-up.');const{amount,method,bankName,refNo,receiptUrl}=r.data||{},amt=Number(amount);if(!Number.isFinite(amt)||amt<=0||amt>100000||!Number.isSafeInteger(Math.round(amt*100)))throw new HttpsError('invalid-argument','Enter a valid amount.');await checkVelocity(db,uid,'createSelfTopup',{ip:getClientIp(r)});const uref=db.collection('users').doc(uid),ref=db.collection('selfTopups').doc();await db.runTransaction(async tx=>{const u=await tx.get(uref);if(!u.exists||!active(u.data()))throw new HttpsError('failed-precondition','Account is not active.');const bal=Number(u.data().walletBalance||0),next=bal+amt;if(!Number.isFinite(bal)||bal<0||!Number.isSafeInteger(Math.round(next*100)))throw new HttpsError('failed-precondition','Wallet balance is invalid.');tx.update(uref,{walletBalance:next});tx.set(ref,{userId:uid,userPhone:caller.phone||'',userName:caller.name||'',userRole:caller.role,amount:amt,points:amt,method:typeof method==='string'?method.trim().slice(0,100):'transfer',bankName:typeof bankName==='string'?bankName.trim().slice(0,100):'',refNo:typeof refNo==='string'?refNo.trim().slice(0,200):'',receiptUrl:typeof receiptUrl==='string'?receiptUrl.trim().slice(0,2048):'',status:'approved',createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});});return{id:ref.id};});
function canTransferTo(role,caller,recipient){if(role==='dealer')return recipient.role==='customer'&&recipient.dealerId===caller.id;if(role==='admin')return recipient.role==='dealer';if(role==='superadmin')return['admin','dealer'].includes(recipient.role);return false;}
exports.transferPoints=onCall({ enforceAppCheck: true },async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!active(caller)||!['dealer','admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Your account cannot transfer points.');const{toUid,amount,note}=r.data||{},amt=Number(amount);if(!toUid||toUid===uid||!Number.isFinite(amt)||amt<=0||amt>100000||!Number.isSafeInteger(Math.round(amt*100)))throw new HttpsError('invalid-argument','Invalid transfer.');const recipient=await getProfile(db,toUid);if(!active(recipient))throw new HttpsError('not-found','That account does not exist or is not active.');if(!canTransferTo(caller.role,caller,recipient))throw new HttpsError('permission-denied','You are not allowed to send points to that account.');const ip=getClientIp(r);await checkVelocity(db,uid,'transferPoints',{ip});const p=await getPricing(db),earn=caller.role==='dealer'&&recipient.role==='customer'?Math.round(amt*(Number(p.dealerEarningPercent)||0)/100*100)/100:0,from=db.collection('users').doc(uid),to=db.collection('users').doc(toUid),tr=db.collection('pointTransfers').doc();await db.runTransaction(async tx=>{const a=await tx.get(from),b=await tx.get(to);if(!a.exists||!b.exists||!active(a.data())||!active(b.data()))throw new HttpsError('failed-precondition','Both accounts must be active.');if(a.data().role!==caller.role||b.data().role!==recipient.role)throw new HttpsError('failed-precondition','Account status changed. Please retry.');const ab=Number(a.data().walletBalance||0),bb=Number(b.data().walletBalance||0),nextA=ab-amt+earn,nextB=bb+amt;if(!Number.isFinite(ab)||ab<0||!Number.isFinite(bb)||bb<0||ab<amt||!Number.isSafeInteger(Math.round(nextA*100))||!Number.isSafeInteger(Math.round(nextB*100)))throw new HttpsError('failed-precondition','Invalid wallet balance.');tx.update(from,{walletBalance:nextA});tx.update(to,{walletBalance:nextB});tx.set(tr,{fromUid:uid,fromName:caller.name||'',fromRole:caller.role,toUid,toName:recipient.name||'',toRole:recipient.role,amount:amt,note:typeof note==='string'?note.trim().slice(0,500):'',participants:[uid,toUid],dealerId:caller.role==='dealer'?uid:caller.dealerId||null,dealerEarning:earn||null,createdAt:admin.firestore.FieldValue.serverTimestamp()});});return{transferId:tr.id};});
const CHARGEABLE={recharge:'rechargePointCostPerUnit',internet:'internetPointCostPerUnit',billpayment:'billPaymentPointCostPerUnit',mobilebanking:null,remittance:null};
async function chargeProduct(request,service,payload,customer){const uid=requireAuth(request),db=admin.firestore(),rates=await getRates(db),calc=recompute(service,payload?.raw,rates),clientAmount=Number(payload?.amount),clientTotal=Number(payload?.total),charge=service==='mobilebanking'||service==='remittance'?calc.total:calc.amount;if(!Number.isFinite(calc.amount)||calc.amount<=0||!Number.isFinite(charge)||charge<=0)throw new HttpsError('invalid-argument','Amount must be greater than zero.');if(Number.isFinite(clientAmount)&&Math.abs(clientAmount-calc.amount)>.01)throw new HttpsError('failed-precondition','Rate changed - please review your order.');if(Number.isFinite(clientTotal)&&Math.abs(clientTotal-calc.total)>.01)throw new HttpsError('failed-precondition','Order total changed - please review your order.');const p=await getPricing(db),settings=await progressionService.getProgressionSettings(),uref=db.collection('users').doc(uid),requestId=payload?.requestId;const txref=db.collection('transactions').doc();const collectionPin=String(crypto.randomInt(0,10000)).padStart(4,'0');const result=await db.runTransaction(async tx=>{const u=await tx.get(uref);if(!u.exists)throw new HttpsError('not-found','Account not found.');const d=u.data();requireSessionMatch(request,d);if(!active(d)||d.role!=='customer')throw new HttpsError('permission-denied','Your customer account is not active.');const wallet=Number(d.walletBalance||0);if(!Number.isFinite(wallet)||wallet<0||!Number.isSafeInteger(Math.round(wallet*100)))throw new HttpsError('failed-precondition','Wallet balance is invalid.');const base=charge*(Number(priceForRole(p,CHARGEABLE[service],d.role))||1),discount=progressionService.discountPercentFromSettings(settings,d.tier),cost=Math.round(base*(1-discount/100)*100)/100;if(!Number.isFinite(cost)||cost<0||!Number.isSafeInteger(Math.round(cost*100))||wallet<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts - top up your wallet first.`);const nextBalance=wallet-cost;if(!Number.isSafeInteger(Math.round(nextBalance*100)))throw new HttpsError('failed-precondition','The resulting wallet balance is invalid.');tx.update(uref,{walletBalance:nextBalance});tx.set(txref,{service:service,details:typeof payload?.details==='string'?payload.details.slice(0,2000):'',amount:calc.amount,total:charge,cost:cost,profit:null,pointsCharged:cost,tierDiscountPercent:discount,chargedServiceKind:service,exchangeRate:calc.exchangeRate,exchangeRateSource:calc.exchangeRateSource,status:'pending',customerId:uid,customerPhone:d.phone||'',resellerId:d.resellerId||null,dealerId:d.resellerId?null:d.dealerId||null,rejected:false,rejectReason:'',pin:collectionPin,raw:{...(payload.raw||{}),...(requestId?{requestId}: {})},createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{cost,role:d.role};});return{id:txref.id,cost:result.cost,collectionPin};}
exports.chargeRecharge=onCall({ enforceAppCheck: true },async r=>chargeProduct(r,'recharge',r.data?.payload,r.data?.customer));
exports.chargeInternetPackage=onCall({ enforceAppCheck: true },async r=>chargeProduct(r,'internet',r.data?.payload,r.data?.customer));
exports.chargeBillPayment=onCall({ enforceAppCheck: true },async r=>chargeProduct(r,'billpayment',r.data?.payload,r.data?.customer));
exports.chargeMobileBanking=onCall({ enforceAppCheck: true },async r=>chargeProduct(r,'mobilebanking',r.data?.payload,r.data?.customer));
exports.chargeRemittance=onCall({ enforceAppCheck: true },async r=>chargeProduct(r,'remittance',r.data?.payload,r.data?.customer));

exports.chargeWallet=onCall({ enforceAppCheck: true },async r=>{const uid=requireAuth(r),db=admin.firestore(),{kind,key}=r.data||{};if(!key||!['webview_access','webview_submit','payment_success','module_subscription'].includes(kind))throw new HttpsError('invalid-argument','Invalid charge.');await checkVelocity(db,uid,'chargeWallet',{ip:getClientIp(r)});const p=await getPricing(db),ref=db.collection('users').doc(uid);return db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Account not found.');const d=s.data();if(!active(d))throw new HttpsError('permission-denied','Your account is not active.');const bal=Number(d.walletBalance||0);if(!Number.isFinite(bal)||bal<0||!Number.isSafeInteger(Math.round(bal*100)))throw new HttpsError('failed-precondition','Wallet balance is invalid.');const now=Date.now();if(kind==='webview_access'){const cost=Number(priceForRole(p,'webviewAccessCost',d.role))||0,win=(Number(p.webviewAccessWindowHours)||0)*3600000,last=d.lastAccessCharge?.[key];if(last&&win>0&&now-last<win)return{charged:false,freeUntil:last+win};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`lastAccessCharge.${key}`]:now});return{charged:true,cost,freeUntil:now+win};}if(kind==='webview_submit'){const cost=Number(priceForRole(p,'webviewSubmitCost',d.role))||0,last=d.webviewSubmitted?.[key];if(last)return{charged:false,submittedAt:last};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`webviewSubmitted.${key}`]:now});return{charged:true,cost,submittedAt:now};}if(kind==='payment_success'){const cost=Number(priceForRole(p,'paymentSuccessCost',d.role))||0,last=d.lastPaymentCharge?.[key];if(last)return{charged:false,chargedAt:last};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`lastPaymentCharge.${key}`]:now});return{charged:true,cost,chargedAt:now};}const keys={notepad:'notepadCost',myDocuments:'myDocumentsCost',salaryOt:'salaryOtCost'},ck=keys[key];if(!ck)throw new HttpsError('invalid-argument','Unknown module.');const cost=Number(priceForRole(p,ck,d.role))||0,win=(Number(p.moduleSubscriptionDays)||30)*86400000,last=d.moduleSubscription?.[key];if(last&&now-last<win)return{charged:false,subscribedUntil:last+win};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`moduleSubscription.${key}`]:now});return{charged:cost>0,cost,subscribedUntil:now+win};});});