const { onCall, HttpsError } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
const progressionService = require('./progressionService');
const { logAudit, logServerError } = require('./logService');
const { checkVelocity, getClientIp } = require('./rateLimitService');
const { checkIpAnomaly } = require('./anomalyService');

const DEFAULT_PRICING={dealerEarningPercent:1.5,webviewAccessCost:2,webviewSubmitCost:2,paymentSuccessCost:3,webviewAccessWindowHours:1,notepadCost:0,myDocumentsCost:0,salaryOtCost:0,moduleSubscriptionDays:30};
const DEFAULT_RATES={mobileBanking:110.5,BD_ACC:30.26,BD_CASH:30.11,NP:37.65,PK:67.79,PH:15.05,LK:81.99,IN:23.5,ID:230,MM:966,remittanceFee:7,rechargeBD:30.26,rechargeIN:23.5,rechargeNP:37.65,rechargeID:230,rechargePK:67.79,rechargeMM:966,rechargePH:15.05,rechargeKH:900};
const RECHARGE_RATE_KEYS={BD:'rechargeBD',IN:'rechargeIN',NP:'rechargeNP',ID:'rechargeID',PK:'rechargePK',MM:'rechargeMM',PH:'rechargePH',KH:'rechargeKH'};
async function getPricing(db){const s=await db.collection('settings').doc('pricing').get();return{...DEFAULT_PRICING,...(s.exists?s.data():{})};}
async function getRates(db){const s=await db.collection('rates').doc('current').get();return{...DEFAULT_RATES,...(s.exists?s.data():{})};}
async function getProfile(db,uid){const s=await db.collection('users').doc(uid).get();return s.exists?{id:s.id,...s.data()}:null;}
function requireAuth(r){if(!r.auth)throw new HttpsError('unauthenticated','You must be signed in.');return r.auth.uid;}
function priceForRole(p,key,role){const v=role&&p.rolePricing&&p.rolePricing[role]&&p.rolePricing[role][key];return v!=null?v:p[key];}
function amountToPoints(n,c,r){const x=Number(n)||0;if(!c||c==='MY')return{x,rate:1};const k=RECHARGE_RATE_KEYS[c];const rate=k&&Number(r[k])>0?Number(r[k]):1;return{x:Math.round(x/rate*100)/100,rate};}
function recompute(service,raw,rates){const r=raw||{};if(service==='recharge'||service==='internet'){const q=amountToPoints(r.amount,r.country,rates);return{amount:q.x,total:q.x,exchangeRate:r.country&&r.country!=='MY'?q.rate:null,exchangeRateSource:r.country&&r.country!=='MY'?RECHARGE_RATE_KEYS[r.country]||null:null};}if(service==='mobilebanking'){const a=Math.round((Number(r.myr)||0)*100)/100;return{amount:a,total:Math.round((a+5)*100)/100,exchangeRate:Number(rates.mobileBanking)||110.5,exchangeRateSource:'mobileBanking'};}if(service==='remittance'){const a=Math.round((Number(r.sendAmt)||0)*100)/100;const fee=Math.round((Number(rates.remittanceFee)||7)*100)/100;const rate=r.country==='BD'?(r.method==='deposit'?Number(rates.BD_ACC):Number(rates.BD_CASH)):Number(rates[r.country])||30.26;return{amount:a,total:Math.round((a+fee)*100)/100,exchangeRate:rate,exchangeRateSource:r.country==='BD'?(r.method==='deposit'?'BD_ACC':'BD_CASH'):r.country};}return{amount:Number(r.amount)||0,total:Number(r.total)||0,exchangeRate:null,exchangeRateSource:null};}

exports.approveTopup=onCall(async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!caller||!['admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Only an admin can approve top-ups.');const{id}=r.data||{};const topupId=id||r.data?.topupId;if(!topupId)throw new HttpsError('invalid-argument','topupId is required.');const ref=db.collection('topups').doc(topupId);try{const out=await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','That top-up request does not exist.');const t=s.data();if(t.status!=='pending')throw new HttpsError('failed-precondition','That request has already been reviewed.');const uref=db.collection('users').doc(t.userId),u=await tx.get(uref);if(!u.exists)throw new HttpsError('not-found','That user account no longer exists.');const pts=Number(t.points||t.amount||0),bal=Number(u.data().walletBalance||0);if(!Number.isFinite(pts)||pts<=0)throw new HttpsError('invalid-argument','Invalid top-up amount.');tx.update(uref,{walletBalance:bal+pts});tx.update(ref,{status:'approved',approvedBy:uid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{userId:t.userId,points:pts};});await logAudit({action:'topup_approved',targetUid:out.userId,performedBy:uid,performedByRole:caller.role,details:{topupId,points:out.points}});return{approved:true};}catch(e){if(e instanceof HttpsError)throw e;await logServerError('approveTopup',e,{userId:uid});throw new HttpsError('internal','Could not approve this top-up.');}});
exports.rejectTopup=onCall(async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!caller||!['admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Only an admin can reject top-ups.');const{topupId,reason}=r.data||{};if(!topupId)throw new HttpsError('invalid-argument','topupId is required.');const ref=db.collection('topups').doc(topupId);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','That top-up request does not exist.');if(s.data().status!=='pending')throw new HttpsError('failed-precondition','That request has already been reviewed.');await ref.update({status:'rejected',rejectReason:reason||'',approvedBy:uid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{rejected:true};});
exports.createSelfTopup=onCall(async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!caller||!['admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Only admin/superadmin can self-top-up.');const{amount,method,bankName,refNo,receiptUrl}=r.data||{},amt=Number(amount);if(!Number.isFinite(amt)||amt<=0)throw new HttpsError('invalid-argument','Enter a valid amount.');await checkVelocity(db,uid,'createSelfTopup',{ip:getClientIp(r)});const uref=db.collection('users').doc(uid),ref=db.collection('selfTopups').doc();await db.runTransaction(async tx=>{const u=await tx.get(uref);if(!u.exists)throw new HttpsError('not-found','Account not found.');tx.update(uref,{walletBalance:Number(u.data().walletBalance||0)+amt});tx.set(ref,{userId:uid,userPhone:caller.phone||'',userName:caller.name||'',userRole:caller.role,amount:amt,points:amt,method:method||'transfer',bankName:bankName||'',refNo:refNo||'',receiptUrl:receiptUrl||'',status:'approved',createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});});return{id:ref.id};});
function canTransferTo(role,caller,recipient){if(role==='dealer')return recipient.dealerId===caller.id;if(role==='admin')return recipient.role==='dealer';if(role==='superadmin')return['admin','dealer'].includes(recipient.role);return false;}
exports.transferPoints=onCall(async r=>{const uid=requireAuth(r),db=admin.firestore(),caller=await getProfile(db,uid);if(!caller||!['dealer','admin','superadmin'].includes(caller.role))throw new HttpsError('permission-denied','Your account cannot transfer points.');const{toUid,amount,note}=r.data||{},amt=Number(amount);if(!toUid||toUid===uid||!Number.isFinite(amt)||amt<=0)throw new HttpsError('invalid-argument','Invalid transfer.');const recipient=await getProfile(db,toUid);if(!recipient||recipient.mergedInto)throw new HttpsError('not-found','That account does not exist.');if(!canTransferTo(caller.role,caller,recipient))throw new HttpsError('permission-denied','You are not allowed to send points to that account.');const ip=getClientIp(r);await checkVelocity(db,uid,'transferPoints',{ip});const p=await getPricing(db),earn=caller.role==='dealer'&&recipient.role==='customer'?Math.round(amt*(Number(p.dealerEarningPercent)||0)/100*100)/100:0;const from=db.collection('users').doc(uid),to=db.collection('users').doc(toUid),tr=db.collection('pointTransfers').doc();await db.runTransaction(async tx=>{const a=await tx.get(from),b=await tx.get(to);const ab=Number(a.data().walletBalance||0);if(ab<amt)throw new HttpsError('failed-precondition','Insufficient balance.');tx.update(from,{walletBalance:ab-amt+earn});tx.update(to,{walletBalance:Number(b.data().walletBalance||0)+amt});tx.set(tr,{fromUid:uid,fromName:caller.name||'',fromRole:caller.role,toUid,toName:recipient.name||'',toRole:recipient.role,amount:amt,note:note||'',participants:[uid,toUid],dealerId:caller.role==='dealer'?uid:caller.dealerId||null,dealerEarning:earn||null,createdAt:admin.firestore.FieldValue.serverTimestamp()});});return{transferId:tr.id};});
exports.boostListing=onCall(async r=>{const uid=requireAuth(r),db=admin.firestore(),{listingId}=r.data||{};if(!listingId)throw new HttpsError('invalid-argument','listingId is required.');const p=await getPricing(db),ref=db.collection('marketplaceListings').doc(listingId),uref=db.collection('users').doc(uid),days=Number(p.listingBoostDurationDays)||7;const out=await db.runTransaction(async tx=>{const l=await tx.get(ref),u=await tx.get(uref);if(!l.exists)throw new HttpsError('not-found','That listing no longer exists.');if(l.data().sellerId!==uid||l.data().status!=='active')throw new HttpsError('permission-denied','You can only boost your own active listing.');const bal=Number(u.data().walletBalance||0),cost=Number(priceForRole(p,'listingBoostCost',u.data().role))||0;if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts to boost.`);const now=Date.now(),old=l.data().featuredUntil?.toMillis?.()||0,until=Math.max(now,old)+days*86400000;tx.update(uref,{walletBalance:bal-cost});tx.update(ref,{featured:true,featuredUntil:admin.firestore.Timestamp.fromMillis(until),updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{cost,featuredUntilMs:until};});return{boosted:true,...out};});
const CHARGEABLE={recharge:'rechargePointCostPerUnit',internet:'internetPointCostPerUnit',mobilebanking:null,remittance:null};
async function chargeProduct(request,service,payload,customer){const uid=requireAuth(request),db=admin.firestore(),rates=await getRates(db),calc=recompute(service,payload?.raw,rates),clientAmount=Number(payload?.amount),clientTotal=Number(payload?.total),charge=service==='mobilebanking'||service==='remittance'?calc.total:calc.amount;if(!Number.isFinite(calc.amount)||calc.amount<0||!Number.isFinite(charge)||charge<0)throw new HttpsError('invalid-argument','Invalid amount.');if(Number.isFinite(clientAmount)&&Math.abs(clientAmount-calc.amount)>.01)throw new HttpsError('failed-precondition','Rate changed - please review your order.');if(Number.isFinite(clientTotal)&&Math.abs(clientTotal-calc.total)>.01)throw new HttpsError('failed-precondition','Order total changed - please review your order.');const p=await getPricing(db),settings=await progressionService.getProgressionSettings(),uref=db.collection('users').doc(uid),requestId=payload?.requestId;const txref=db.collection('transactions').doc();const result=await db.runTransaction(async tx=>{const u=await tx.get(uref);if(!u.exists)throw new HttpsError('not-found','Account not found.');const d=u.data(),base=charge*(Number(priceForRole(p,CHARGEABLE[service],d.role))||1),discount=progressionService.discountPercentFromSettings(settings,d.tier),cost=Math.round(base*(1-discount/100)*100)/100;if(Number(d.walletBalance||0)<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts - top up your wallet first.`);tx.update(uref,{walletBalance:Number(d.walletBalance||0)-cost});tx.set(txref,{service:payload.service,details:payload.details||'',amount:calc.amount,total:charge,cost:payload.cost||0,profit:payload.profit||0,pointsCharged:cost,tierDiscountPercent:discount,chargedServiceKind:service,exchangeRate:calc.exchangeRate,exchangeRateSource:calc.exchangeRateSource,status:'pending',customerId:uid,customerPhone:d.phone||'',resellerId:d.resellerId||null,dealerId:d.resellerId?null:d.dealerId||null,rejected:false,rejectReason:'',pin:'',raw:{...(payload.raw||{}),...(requestId?{requestId}: {})},createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{cost,role:d.role};});return{id:txref.id,cost:result.cost};}
exports.chargeRecharge=onCall(async r=>chargeProduct(r,'recharge',r.data?.payload,r.data?.customer));
exports.chargeInternetPackage=onCall(async r=>chargeProduct(r,'internet',r.data?.payload,r.data?.customer));
exports.chargeMobileBanking=onCall(async r=>chargeProduct(r,'mobilebanking',r.data?.payload,r.data?.customer));
exports.chargeRemittance=onCall(async r=>chargeProduct(r,'remittance',r.data?.payload,r.data?.customer));
async function rejectTx(r,service){const uid=requireAuth(r),db=admin.firestore(),{transactionId,reason}=r.data||{};if(!transactionId)throw new HttpsError('invalid-argument','transactionId is required.');const caller=await getProfile(db,uid);if(!caller||!['admin','superadmin','dealer','reseller'].includes(caller.role))throw new HttpsError('permission-denied','Only staff can reject an order.');const ref=db.collection('transactions').doc(transactionId);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','That order does not exist.');const d=s.data();if(d.chargedServiceKind!==service)throw new HttpsError('failed-precondition','Wrong service.');if(d.status!=='pending'||d.claimedBy)throw new HttpsError('failed-precondition','That order has already been accepted.');tx.update(ref,{rejected:true,rejectReason:reason||'Rejected by staff.',rejectedBy:uid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});});return{rejected:true};}
exports.rejectRechargeTransaction=onCall(r=>rejectTx(r,'recharge'));exports.rejectInternetPackageTransaction=onCall(r=>rejectTx(r,'internet'));exports.rejectMobileBankingTransaction=onCall(r=>rejectTx(r,'mobilebanking'));exports.rejectRemittanceTransaction=onCall(r=>rejectTx(r,'remittance'));
exports.chargeWallet=onCall(async r=>{const uid=requireAuth(r),db=admin.firestore(),{kind,key}=r.data||{};if(!key||!['webview_access','webview_submit','payment_success','module_subscription'].includes(kind))throw new HttpsError('invalid-argument','Invalid charge.');await checkVelocity(db,uid,'chargeWallet',{ip:getClientIp(r)});const p=await getPricing(db),ref=db.collection('users').doc(uid);return db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Account not found.');const d=s.data(),bal=Number(d.walletBalance||0),now=Date.now();if(kind==='webview_access'){const cost=Number(priceForRole(p,'webviewAccessCost',d.role))||0,win=(Number(p.webviewAccessWindowHours)||0)*3600000,last=d.lastAccessCharge?.[key];if(last&&win>0&&now-last<win)return{charged:false,freeUntil:last+win};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`lastAccessCharge.${key}`]:now});return{charged:true,cost,freeUntil:now+win};}if(kind==='webview_submit'){const cost=Number(priceForRole(p,'webviewSubmitCost',d.role))||0,last=d.webviewSubmitted?.[key];if(last)return{charged:false,submittedAt:last};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`webviewSubmitted.${key}`]:now});return{charged:true,cost,submittedAt:now};}if(kind==='payment_success'){const cost=Number(priceForRole(p,'paymentSuccessCost',d.role))||0,last=d.lastPaymentCharge?.[key];if(last)return{charged:false,chargedAt:last};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`lastPaymentCharge.${key}`]:now});return{charged:true,cost,chargedAt:now};}const keys={notepad:'notepadCost',myDocuments:'myDocumentsCost',salaryOt:'salaryOtCost'},ck=keys[key];if(!ck)throw new HttpsError('invalid-argument','Unknown module.');const cost=Number(priceForRole(p,ck,d.role))||0,win=(Number(p.moduleSubscriptionDays)||30)*86400000,last=d.moduleSubscription?.[key];if(last&&now-last<win)return{charged:false,subscribedUntil:last+win};if(bal<cost)throw new HttpsError('failed-precondition',`You need ${cost} pts.`);tx.update(ref,{walletBalance:bal-cost,[`moduleSubscription.${key}`]:now});return{charged:cost>0,cost,subscribedUntil:now+win};});});
