import { doc, getDoc, onSnapshot, Timestamp } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { db, functions } from './config';
import { PAY_FREQUENCIES, OT_CALCULATION_METHODS } from '../data/salaryConstants';

const SETTINGS_DOC_ID = 'current';
function settingsRef(userId) { return doc(db, 'users', userId, 'salarySettings', SETTINGS_DOC_ID); }
export async function getSalarySettings(userId) { if (!userId) throw new Error('Not authenticated'); const snap = await getDoc(settingsRef(userId)); return snap.exists() ? hydrate(snap.data()) : null; }
export function subscribeSalarySettings(userId, onChange, onError) { if (!userId) { onError?.(new Error('Not authenticated')); return () => {}; } return onSnapshot(settingsRef(userId), snap => onChange(snap.exists() ? hydrate(snap.data()) : null), err => onError?.(err)); }
export async function saveSalarySettings(userId, settings) { if (!userId) throw new Error('Not authenticated'); await httpsCallable(functions, 'saveSalarySettings')({ userId, settings: { basicSalary: settings.basicSalary, payFrequency: settings.payFrequency || PAY_FREQUENCIES.MONTHLY, normalHoursPerDay: settings.normalHoursPerDay, workingDaysPerWeek: settings.workingDaysPerWeek, restDay: settings.restDay ?? null, employmentType: settings.employmentType ?? null, currency: settings.currency || 'RM', country: settings.country || 'Malaysia', otCalculationMethod: settings.otCalculationMethod || OT_CALCULATION_METHODS.DEFAULT, customOtRate: settings.customOtRate ?? null, remindersEnabled: settings.remindersEnabled ?? true } }); }
function hydrate(data) { const toMillis = v => (v instanceof Timestamp ? v.toMillis() : v ?? null); return { basicSalary: data.basicSalary ?? 0, payFrequency: data.payFrequency ?? PAY_FREQUENCIES.MONTHLY, normalHoursPerDay: data.normalHoursPerDay ?? 8, workingDaysPerWeek: data.workingDaysPerWeek ?? 6, restDay: data.restDay ?? null, employmentType: data.employmentType ?? null, currency: data.currency ?? 'RM', country: data.country ?? 'Malaysia', otCalculationMethod: data.otCalculationMethod ?? OT_CALCULATION_METHODS.DEFAULT, customOtRate: data.customOtRate ?? null, remindersEnabled: data.remindersEnabled ?? true, createdAt: toMillis(data.createdAt), updatedAt: toMillis(data.updatedAt) }; }
