import React, { useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as Print from 'expo-print';
import { countries } from '../data/countries';
import { useTheme } from '../theme/ThemeContext';

const COMPANY_NAME = 'SatuLink Solutions Sdn Bhd (1641555-U)';
const COMPANY_ADDRESS = 'Address: To be set';
const POWERED_BY = 'Powered by OTR';
const LOGO_URL = 'https://mysheba.top/assets/images/logo.png';
const esc = (v) => String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
const val = (v) => v == null || v === '' ? '-' : String(v);
const money = (v,c='MYR') => { const n=Number(v); return `${Number.isFinite(n)?n.toFixed(2):'0.00'} [${c}]`; };
const countryName = (code) => countries.find((x)=>x.code===code)?.name || code || '';
const formatDate = (v) => { if(!v)return '-'; try { const d=v?.toDate?v.toDate():new Date(v); return Number.isNaN(d.getTime())?val(v):d.toLocaleString(); } catch(_){return val(v);} };

export function buildReceiptHtml(tx={}, profile={}, operator='') {
  const raw=tx.raw||tx.serviceData||{};
  const country=countryName(raw.country||tx.country), curr=raw.currency||raw.receiveCurrency||raw.curr||tx.receiveCurrency||'';
  const send=raw.sendAmt??tx.amount??0, fee=raw.transferFee??tx.transferFee??tx.fee??0;
  const total=raw.total??tx.total??(Number(send)+Number(fee)), rate=raw.receivingRate??tx.receivingRate??tx.exchangeRate??'';
  const receive=raw.receiveAmount??tx.receiveAmount??(Number(send)*Number(rate||0));
  const method=raw.method==='deposit'?'BANK DEPOSIT':raw.method==='cash'?'CASH PICKUP':raw.method==='ewallet'?'EWALLET':val(raw.method||tx.method);
  const receiver=`${raw.receiverFirstName||''} ${raw.receiverLastName||''}`.trim(), sender=raw.senderName||tx.senderName||profile.name||'';
  const receiptNo=tx.id||tx.txId||tx.reference||raw.reference||'', created=formatDate(tx.createdAt||tx.updatedAt||raw.createdAt);
  // `approvedBy` is written by the completion action when available. For
  // older records, operatorName/operator remain compatible fallbacks.
  const approvedBy=tx.approvedByName||tx.approvedBy||operator||tx.operatorName||tx.operator||'';
  const op=operator||tx.operatorName||tx.operator||approvedBy;
  const senderRows=[['Senders Name',sender],['Cust ID',raw.customerId||profile.customerId||profile.custId||tx.customerId],['PASSPORT',raw.senderPassportNo||tx.senderPassportNo],['Place of Issue',raw.senderPassportIssuePlace||raw.passportPlaceOfIssue||raw.nationality],['Expire Date',raw.senderPassportExpiry],['Issue Date',raw.senderPassportIssueDate],['Skilled labor',raw.skill||raw.skilledLabor],['Address',raw.senderAddress],['Mobile No.',raw.senderPhone||tx.senderPhone||profile.phone],['Date of Birth',raw.senderDob||raw.dateOfBirth],['Name of Employer',raw.employerName||raw.employer],['Gender',raw.gender],['Occupation',raw.occupation],['Source of funds',raw.sourceOfFunds||raw.sourceFunds],['Nationality',raw.nationality],['Purpose',raw.purpose],['Relation',raw.receiverRelationship]];
  const receiverRows=[['Payout Country',`${country}${country&&method?' - ':''}${method}`],['Mobile No',raw.receiverPhone||tx.receiverPhone],["Receiver's Name",receiver||tx.receiverName],['Address',raw.receiverAddress||raw.receiverCountry||country],['Bank Name',raw.receiverBankName],['Branch',raw.receiverBranch],['Place of Issue',raw.receiverPlaceOfIssue||country],['Bank Account No',raw.receiverAccountNumber],['Pickup Network',raw.receiverPickupNetwork],['Pickup City',raw.receiverPickupCity],['Receiver ID',raw.receiverIdType?`${raw.receiverIdType} - ${raw.receiverIdNumber||''}`:''],['Wallet Provider',raw.receiverWalletProvider],['Wallet Number',raw.receiverWalletNumber],['Routing Number',raw.receiverRoutingNumber]].filter(([,v])=>v!=='');
  const rows=(rs)=>rs.map(([l,v])=>`<tr><td class="label">${esc(l)}</td><td>${esc(val(v))}</td></tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:10mm}body{font-family:Arial;color:#111;font-size:10px;margin:0}.receipt{border:1px solid #111;padding:8px}.header{display:flex;align-items:center;border-bottom:1px solid #111;padding-bottom:7px}.logo{width:125px;max-height:48px;object-fit:contain}.company{flex:1;text-align:center}.company b{font-size:15px}.copy{text-align:right;font-size:11px}.copy b{color:#b22222;text-decoration:underline}.grid{display:grid;grid-template-columns:1fr 250px;gap:10px}.box{border:1px solid #111;margin-top:7px}.box h3{font-size:11px;margin:0;padding:5px;border-bottom:1px solid #111}.box table{width:100%;border-collapse:collapse}.box td{padding:3px 4px;vertical-align:top}.label{font-weight:bold;width:19%}.side .cell{border-bottom:1px solid #555;padding:6px}.side .big{font-size:18px;font-weight:bold}.terms{border:1px solid #111;margin-top:8px;padding:6px;font-size:8px}.sign{display:flex;justify-content:space-between;padding:10px 4px 3px;font-size:12px;font-weight:bold}.powered{text-align:right;font-size:8px;margin-top:5px}</style></head><body><div class="receipt"><div class="header"><img class="logo" src="${esc(LOGO_URL)}"><div class="company"><b>MySheba</b><br><b>${esc(COMPANY_NAME)}</b><br>${esc(COMPANY_ADDRESS)}</div><div class="copy"><b>Customer Copy</b><br>To Send Form</div></div><div class="grid"><div><div class="box"><h3>SENDER INFORMATION</h3><table>${rows(senderRows)}</table></div><div class="box"><h3>RECEIVER INFORMATION</h3><table>${rows(receiverRows)}</table></div></div><div class="side box"><div class="cell">GST Registration ID: ${esc(val(tx.gstRegistrationId||raw.gstRegistrationId))}</div><div class="cell"><b>PINNO</b><br><span class="big">${esc(val(tx.pinNo||tx.reference||receiptNo))}</span></div><div class="cell"><b>Approved By: ${esc(val(approvedBy))}</b><br>${esc(created)}</div><div class="cell"><b>Collected Amount</b><br>${esc(money(total))}</div><div class="cell"><b>Service Charge</b><br>${esc(money(fee))}</div><div class="cell"><b>GST:</b><br>${esc(money(tx.gst||raw.gst||0))}</div><div class="cell"><b>Transfer Amount</b><br>${esc(money(send))}</div><div class="cell">1 MYR = ${esc(val(rate))} [${esc(curr)}]</div><div class="cell"><b>Receive Amount</b><br><span class="big">${esc(money(receive,curr))}</span></div><div class="cell">Serial: ${esc(val(tx.serial||tx.serialNo||receiptNo))}</div><div class="cell">${esc(val(raw.receiverBankName||raw.receiverPickupNetwork||raw.receiverWalletProvider||method))}</div></div></div><div class="terms">THE TERMS AND CONDITIONS GOVERNING THE MONEY TRANSFER SERVICE ARE DISPLAYED AT ${esc(COMPANY_NAME)}. BY SIGNING THIS FORM YOU ARE AGREEING TO THOSE TERMS AND CONDITIONS.</div><div class="sign"><span>Customer's Signature __________________________</span><span>Operator :(${esc(val(op))}) __________________________</span></div><div class="powered">${esc(POWERED_BY)}</div></div></body></html>`;
}

export default function RemittanceReceipt({transaction={},profile={},operator='',onClose}) {
  const {colors}=useTheme(); const [printing,setPrinting]=useState(false); const html=useMemo(()=>buildReceiptHtml(transaction,profile,operator),[transaction,profile,operator]);
  const raw=transaction.raw||{};
  const approvedBy=transaction.approvedByName||transaction.approvedBy||operator||transaction.operatorName||transaction.operator||'';
  const senderRows=[['Senders Name',raw.senderName||transaction.senderName||profile.name],['Cust ID',raw.customerId||profile.customerId||transaction.customerId],['PASSPORT',raw.senderPassportNo],['Place of Issue',raw.senderPassportIssuePlace||raw.passportPlaceOfIssue||raw.nationality],['Expire Date',raw.senderPassportExpiry],['Issue Date',raw.senderPassportIssueDate],['Skilled labor',raw.skill||raw.skilledLabor],['Address',raw.senderAddress],['Mobile No.',raw.senderPhone||profile.phone],['Date of Birth',raw.senderDob],['Name of Employer',raw.employerName],['Gender',raw.gender],['Occupation',raw.occupation],['Source of funds',raw.sourceOfFunds],['Nationality',raw.nationality],['Purpose',raw.purpose],['Relation',raw.receiverRelationship]];
  const receiverRows=[['Payout Country',countryName(raw.country||transaction.country)],['Receiver Name',`${raw.receiverFirstName||''} ${raw.receiverLastName||''}`.trim()],['Mobile No',raw.receiverPhone],['Bank Name',raw.receiverBankName],['Branch',raw.receiverBranch],['Place of Issue',raw.receiverPlaceOfIssue],['Bank Account No',raw.receiverAccountNumber],['Routing Number',raw.receiverRoutingNumber],['Pickup Network',raw.receiverPickupNetwork],['Pickup City',raw.receiverPickupCity],['Wallet Provider',raw.receiverWalletProvider],['Wallet Number',raw.receiverWalletNumber]];
  return <View style={[styles.container,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content}><View style={styles.preview}><Text style={styles.brand}>MySheba</Text><Text style={styles.company}>{COMPANY_NAME}</Text><Text style={styles.address}>{COMPANY_ADDRESS}</Text><Text style={styles.copy}>Customer Copy</Text><Section title="SENDER INFORMATION" rows={senderRows}/><Section title="RECEIVER INFORMATION" rows={receiverRows}/><View style={styles.sidePreview}><Row label="GST Registration ID" value={transaction.gstRegistrationId||raw.gstRegistrationId}/><Row label="PINNO" value={transaction.pinNo||transaction.reference||transaction.id}/><Row label="Approved By" value={approvedBy}/><Row label="Collected Amount" value={money(transaction.total??transaction.amount??0)}/><Row label="Service Charge" value={money(raw.transferFee??transaction.fee??0)}/><Row label="GST" value={money(transaction.gst||raw.gst||0)}/><Row label="Transfer Amount" value={money(raw.sendAmt??transaction.amount??0)}/><Row label="Exchange Rate" value={raw.receivingRate||transaction.exchangeRate}/><Row label="Receive Amount" value={money(raw.receiveAmount||transaction.receiveAmount||((raw.sendAmt||transaction.amount||0)*(raw.receivingRate||transaction.exchangeRate||0)),raw.currency||transaction.receiveCurrency||'')}/><Row label="Serial" value={transaction.serial||transaction.id}/><Row label="Payout" value={raw.receiverBankName||raw.receiverPickupNetwork||raw.receiverWalletProvider||raw.method}/></View><Text style={styles.terms}>THE TERMS AND CONDITIONS GOVERNING THE MONEY TRANSFER SERVICE ARE DISPLAYED AT {COMPANY_NAME}. BY SIGNING THIS FORM YOU ARE AGREEING TO THOSE TERMS AND CONDITIONS.</Text><View style={styles.sign}><Text>Customer's Signature __________________</Text><Text>Operator :({operator||approvedBy||'-'}) __________________</Text></View><Text style={styles.powered}>{POWERED_BY}</Text></View><TouchableOpacity style={styles.button} onPress={printReceipt} disabled={printing}>{printing?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Print / Save Receipt PDF</Text>}</TouchableOpacity>{onClose&&<TouchableOpacity onPress={onClose}><Text style={styles.close}>Close</Text></TouchableOpacity>}</ScrollView></View>;
}
function Section({title,rows}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{rows.map(([l,v],i)=><Row key={`${l}-${i}`} label={l} value={v}/>)}</View>}
function Row({label,value}){return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{val(value)}</Text></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:12},preview:{backgroundColor:'#fff',borderWidth:1,borderColor:'#111',padding:8},brand:{fontSize:22,fontWeight:'800',textAlign:'center'},company:{fontSize:13,fontWeight:'800',textAlign:'center'},address:{fontSize:10,textAlign:'center'},copy:{fontSize:12,fontWeight:'800',color:'#b22222',textAlign:'right',marginVertical:5},section:{borderWidth:1,borderColor:'#111',marginTop:7},sectionTitle:{fontSize:11,fontWeight:'800',padding:5,borderBottomWidth:1,borderColor:'#111'},row:{flexDirection:'row',paddingVertical:3,paddingHorizontal:4},rowLabel:{width:'35%',fontWeight:'700',fontSize:10},rowValue:{flex:1,fontSize:10},sidePreview:{borderWidth:1,borderColor:'#111',marginTop:7},terms:{borderWidth:1,borderColor:'#111',marginTop:8,padding:6,fontSize:8},sign:{flexDirection:'row',justifyContent:'space-between',marginTop:12},powered:{fontSize:9,textAlign:'right',marginTop:5},button:{marginTop:12,padding:14,borderRadius:8,backgroundColor:'#111',alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},close:{textAlign:'center',padding:14,fontWeight:'700'}});
