// Generic, brand-neutral service icons used by the Home grid.
// No country flags, telecom operator logos, or bank logos are used here.
export const SERVICE_GRID_ICONS = {
  recharge: '↻',
  mobilebanking: '▣',
  internet: '⌁',
  remittance: '⇄',
  bus: '▰',
  train: '▤',
  flight: '✈',
  fomema: '+',
  visa: '▤',
  mydigital: '▱',
  passport: '▯',
  marketplace: '□',
  myDocuments: '▤',
  salary: '◉',
  esim: '⌁',
  social: '●',
  support: '?',
  history: '◷',
  chat: '◌',
  myAccount: '▤',
  profile: '●',
  notepad: '▤',
  gamePoints: '◆',
  gamePointsGift: '◇',
  moreFeaturesTile: '⋯',
};
