import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BadgeCheck, CheckCircle2, Clock3, FileSearch, MessageSquare, Search, Shield, UserRound, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { buildInvestigationSummary, getInvestigationKyc, getInvestigationLogs, getInvestigationTickets, getInvestigationTransactions, searchInvestigationUsers, type InvestigationKyc, type InvestigationLog, type InvestigationSummary, type InvestigationTicket, type InvestigationTransaction } from '../services/investigationService';
import type { AdminUserRow } from '../services/userManagementService';

const money=(n:number)=>`RM ${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
type TimelineEvent={id:string;kind:'transaction'|'kyc'|'support'|'audit'|'activity';title:string;detail:string;status:string;when:string;timestampMs:number|null};
function buildTimeline(tx:InvestigationTransaction[],tickets:InvestigationTicket[],kyc:InvestigationKyc[],logs:InvestigationLog[]):TimelineEvent[]{return[...tx.map(x=>({id:`tx-${x.id}`,kind:'transaction' as const,title:x.service||'Transaction',detail:money(x.total),status:x.rejected?'Rejected':x.status,when:x.createdAt||'Unknown date',timestampMs:x.timestampMs})),...kyc.map(x=>({id:`kyc-${x.id}`,kind:'kyc' as const,title:'Identity verification',detail:x.documentType||'Verification request',status:x.status,when:x.submittedAt||'Unknown date',timestampMs:x.timestampMs})),...tickets.map(x=>({id:`ticket-${x.id}`,kind:'support' as const,title:x.subject,detail:x.message||'Support ticket',status:x.status.replace('_',' '),when:x.createdAt||'Unknown date',timestampMs:x.timestampMs})),...logs.map(x=>({id:`${x.type}-${x.id}`,kind:x.type,title:x.summary,detail:x.type==='audit'?'Audit event':'Activity event',status:x.type,when:x.createdAt||'Unknown date',timestampMs:x.timestampMs}))].sort((a,b)=>(b.timestampMs??0)-(a.timestampMs??0));}
function eventIcon(k:TimelineEvent['kind']){return k==='transaction'?<Activity size={17}/>:k==='kyc'?<BadgeCheck size={17}/>:k==='support'?<MessageSquare size={17}/>:k==='audit'?<Shield size={17}/>:<Clock3 size={17}/>}
function eventClass(k:TimelineEvent['kind']){return k==='transaction'?'bg-blue-50 text-blue-700':k==='kyc'?'bg-emerald-50 text-emerald-700':k==='support'?'bg-violet-50 text-violet-700':k==='audit'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700'}
function Metric({icon,label,value,sub}:{icon:React.ReactNode;label:string;value:string|number;sub?:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-slate-500">{icon}<span className="text-xs font-bold">{label}</span></div><div className="mt-2 text-xl font-extrabold text-[#0b2447]">{value}</div>{sub&&<div className="mt-1 text-[11px] text-slate-400">{sub}</div>}</div>}
function Empty({text}:{text:string}){return <div className="rounded-xl bg-slate-50 p-6 text-center text-xs text-slate-500">{text}</div>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 border-b border-slate-100 pb-3 text-[#0b2447]"><span className="text-[#00a99d]">{icon}</span><h3 className="font-extrabold">{title}</h3></div>{children}</section>}
function RiskCard({icon,title,text,tone,onClick}:{icon:React.ReactNode;title:string;text:string;tone:'red'|'amber'|'green'|'blue';onClick?:()=>void}){const c=tone==='red'?'border-red-200 bg-red-50 text-red-700':tone==='amber'?'border-amber-200 bg-amber-50 text-amber-700':tone==='green'?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-blue-200 bg-blue-50 text-blue-700';return <button disabled={!onClick} onClick={onClick} className={`w-full rounded-xl border p-4 text-left ${c} ${onClick?'hover:shadow-sm':''}`}><div className="flex items-start gap-3">{icon}<div><b className="block text-sm">{title}</b><span className="mt-1 block text-xs opacity-80">{text}</span>{onClick&&<span className="mt-2 block text-[10px] font-extrabold uppercase tracking-wide">Open related queue →</span>}</div></div></button>}
export default function AdminInvestigationCenterPage(){
 const {profile}=useAuth(); const navigate=useNavigate();
 const [term,setTerm]=useState(''); const [users,setUsers]=useState<AdminUserRow[]>([]); const [selected,setSelected]=useState<AdminUserRow|null>(null); const [tx,setTx]=useState<InvestigationTransaction[]>([]); const [tickets,setTickets]=useState<InvestigationTicket[]>([]); const [logs,setLogs]=useState<InvestigationLog[]>([]); const [kyc,setKyc]=useState<InvestigationKyc[]>([]); const [loading,setLoading]=useState(false); const [detailLoading,setDetailLoading]=useState(false); const [error,setError]=useState('');
 async function search(){const q=term.trim();if(!q)return;setLoading(true);setError('');setSelected(null);try{setUsers(await searchInvestigationUsers(q));}catch(e){console.error(e);setError('Search failed. Check Firestore access and connection.')}finally{setLoading(false)}}
 async function inspect(u:AdminUserRow){setSelected(u);setDetailLoading(true);setError('');setTx([]);setTickets([]);setLogs([]);setKyc([]);try{const[a,b,c,d]=await Promise.all([getInvestigationTransactions(u.uid),getInvestigationTickets(u.uid),getInvestigationLogs(u.uid),getInvestigationKyc(u.uid)]);setTx(a);setTickets(b);setLogs(c);setKyc(d);}catch(e){console.error(e);setError('Some investigation data could not be loaded. Available sections are shown.')}finally{setDetailLoading(false)}}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('investigation-search')?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 const summary:InvestigationSummary=useMemo(()=>buildInvestigationSummary(tx,tickets,kyc),[tx,tickets,kyc]); const latestKyc=kyc[0]; const timeline=useMemo(()=>buildTimeline(tx,tickets,kyc,logs),[tx,tickets,kyc,logs]);
 return <div className="space-y-6 p-4 sm:p-6">
  <header className="rounded-3xl bg-gradient-to-r from-[#0b2447] via-[#155e9c] to-[#00a99d] p-6 text-white shadow-lg"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-white/80"><FileSearch size={18}/> Investigation & Search</div><h1 className="text-2xl font-extrabold sm:text-3xl">Admin Search & Investigation Center</h1><p className="mt-2 max-w-2xl text-sm text-white/75">Search an account and inspect its operational footprint across identity, transactions, support and available audit history.</p></div><button onClick={()=>navigate('/activity-center')} className="rounded-xl bg-white/15 px-4 py-2.5 text-sm font-bold backdrop-blur hover:bg-white/25">Activity Center</button></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-3.5 text-slate-400"/><input id="investigation-search" value={term} onChange={e=>setTerm(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Name, email or phone…" className="w-full rounded-xl border-0 bg-white py-3 pl-10 pr-3 text-sm text-slate-900 outline-none"/></div><button onClick={search} disabled={loading||!term.trim()} className="rounded-xl bg-[#00a99d] px-6 py-3 text-sm font-extrabold disabled:opacity-50">{loading?'Searching…':'Search account'}</button></div><p className="mt-2 text-xs text-white/60">Tip: press Ctrl/Cmd + K to focus search. Search uses the existing users directory and does not create a new index.</p></header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]">
   <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-[#0b2447]">Matching accounts</h2><p className="text-xs text-slate-500">{users.length} result{users.length===1?'':'s'}</p></div><UserRound className="text-slate-300" size={22}/></div></div><div className="divide-y divide-slate-100">{users.map(u=><button key={u.uid} onClick={()=>inspect(u)} className={`flex w-full items-center gap-3 p-4 text-left hover:bg-slate-50 ${selected?.uid===u.uid?'bg-[#f0fbfa] ring-1 ring-inset ring-[#00a99d]':''}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#e8f7f5] font-extrabold text-[#008f85]">{u.name?.[0]?.toUpperCase()||'U'}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-[#0b2447]">{u.name}</b><span className="block truncate text-xs text-slate-500">{u.email||u.phone||u.uid}</span></span><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold capitalize">{u.role}</span></button>)}{!loading&&!users.length&&<div className="p-10 text-center text-sm text-slate-500">Enter a name, email or phone number to begin.</div>}</div></section>
   <main className="space-y-6">{selected?<>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-[#e8f7f5] text-xl font-extrabold text-[#008f85]">{selected.name?.[0]?.toUpperCase()||'U'}</span><div><h2 className="text-xl font-extrabold text-[#0b2447]">{selected.name}</h2><div className="mt-1 flex flex-wrap gap-2 text-xs text-slate-500"><span>{selected.email||'No email'}</span><span>•</span><span>{selected.phone||'No phone'}</span><span>•</span><span className="font-mono">{selected.uid}</span></div></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${selected.disabled?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{selected.disabled?'Disabled':'Active'}</span><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold capitalize text-blue-700">{selected.role}</span><button onClick={()=>navigate('/user-operations')} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">User controls</button></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<Activity size={18}/>} label="Transactions" value={tx.length}/><Metric icon={<CheckCircle2 size={18}/>} label="Completed value" value={money(summary.completedValue)}/><Metric icon={<MessageSquare size={18}/>} label="Open support" value={summary.openTickets}/><Metric icon={<BadgeCheck size={18}/>} label="KYC status" value={summary.kycStatus}/></div>
    <Panel title="Risk & Attention" icon={<AlertTriangle size={18}/>}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><RiskCard icon={<XCircle size={18}/>} title={`${summary.rejectedTransactions} rejected`} text={summary.rejectedValue?`${money(summary.rejectedValue)} rejected value in visible records.`:'No rejected transactions in the visible records.'} tone={summary.rejectedTransactions?'red':'green'} onClick={summary.rejectedTransactions?()=>navigate('/fraud-risk'):undefined}/><RiskCard icon={<Clock3 size={18}/>} title={`${summary.openTickets} open support`} text={summary.openTickets?'This account has unresolved support work.':'No unresolved support tickets found.'} tone={summary.openTickets?'amber':'green'} onClick={summary.openTickets?()=>navigate('/support-operations'):undefined}/><RiskCard icon={<Activity size={18}/>} title={`${summary.highValueTransactions} high-value`} text={summary.highValueTransactions?`${summary.highValueTransactions} visible transaction(s) at or above RM 10,000.`:'No visible transaction at or above RM 10,000.'} tone={summary.highValueTransactions?'blue':'green'} onClick={summary.highValueTransactions?()=>navigate('/financial-risk'):undefined}/><RiskCard icon={<BadgeCheck size={18}/>} title={`KYC: ${summary.kycStatus}`} text={summary.kycStatus==='rejected'?'Identity verification was rejected.':summary.kycStatus==='pending'?'Identity verification needs review.':summary.kycStatus==='approved'?'Identity verification is approved.':'No verification request found.'} tone={summary.kycStatus==='rejected'?'red':summary.kycStatus==='pending'?'amber':summary.kycStatus==='approved'?'green':'blue'} onClick={summary.kycStatus==='pending'||summary.kycStatus==='rejected'?()=>navigate('/verification'):undefined}/></div><p className="mt-3 text-[11px] text-slate-400">These are attention indicators from the available investigation records, not automatic fraud or AML decisions.</p></Panel>
    <Panel title="Financial snapshot" icon={<Activity size={18}/>}><div className="grid gap-3 sm:grid-cols-4"><Metric icon={<Activity size={16}/>} label="Visible value" value={money(summary.totalValue)}/><Metric icon={<CheckCircle2 size={16}/>} label="Completed" value={money(summary.completedValue)}/><Metric icon={<Clock3 size={16}/>} label="Pending" value={money(summary.pendingValue)}/><Metric icon={<XCircle size={16}/>} label="Rejected" value={money(summary.rejectedValue)}/></div></Panel>
    <Panel title="Unified account timeline" icon={<Clock3 size={18}/>}><p className="mb-4 text-xs text-slate-500">Chronological view of available transactions, KYC, support and audit/activity records.</p>{detailLoading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-16 animate-pulse rounded-xl bg-slate-50"/>)}</div>:timeline.length?<div className="relative space-y-1 pl-2 before:absolute before:bottom-2 before:left-[22px] before:top-2 before:w-px before:bg-slate-200">{timeline.slice(0,100).map(event=><div key={event.id} className="relative flex gap-3 py-2"><div className={`z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full ring-4 ring-white ${eventClass(event.kind)}`}>{eventIcon(event.kind)}</div><div className="min-w-0 flex-1 rounded-xl border border-slate-100 bg-slate-50/60 p-3"><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><b className="block truncate text-sm text-[#0b2447]">{event.title}</b><span className="block text-xs text-slate-500">{event.detail}</span></div><div className="flex shrink-0 gap-2"><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold capitalize text-slate-600">{event.kind}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${event.status==='completed'||event.status==='approved'?'bg-emerald-50 text-emerald-700':event.status.toLowerCase()==='rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{event.status}</span></div></div><div className="mt-2 text-[11px] text-slate-400">{event.when}</div></div></div>)}</div>:<Empty text="No timeline events found in the available investigation scope."/>}</Panel>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="Identity / KYC" icon={<BadgeCheck size={18}/>}><div>{latestKyc?<><div className="flex items-center justify-between"><div><b className="text-sm text-[#0b2447]">Verification request</b><p className="text-xs text-slate-500">{latestKyc.submittedAt||'Unknown submission date'} · {latestKyc.id}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold capitalize">{latestKyc.status}</span></div><div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b>Document:</b> {latestKyc.documentType||'Not specified'}{latestKyc.rejectionReason&&<><br/><b>Reason:</b> {latestKyc.rejectionReason}</>}</div><button onClick={()=>navigate('/verification')} className="mt-3 w-full rounded-xl border border-[#00a99d] px-3 py-2 text-xs font-bold text-[#008f85]">Open Verification Queue</button></>:<Empty text="No verification request found for this account."/>}</div></Panel>
     <Panel title="Transaction history" icon={<Activity size={18}/>}><div>{tx.length?<div className="space-y-2">{tx.slice(0,20).map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="min-w-0 flex-1"><b className="block truncate text-sm text-[#0b2447]">{x.service||'Transaction'}</b><span className="text-xs text-slate-500">{x.createdAt||'Unknown date'} · {x.id}</span></span><span className="text-right"><b className="block text-sm text-[#0b2447]">{money(x.total)}</b><span className={`text-xs font-bold ${x.rejected?'text-red-600':x.status==='completed'?'text-emerald-600':'text-amber-600'}`}>{x.rejected?'Rejected':x.status}</span></span></div>)}</div>:<Empty text="No customer transactions found."/>}<div className="mt-3 border-t border-slate-100 pt-3 text-xs font-semibold text-slate-500">Visible transaction value: {money(summary.totalValue)}</div></div></Panel>
     <Panel title="Support history" icon={<MessageSquare size={18}/>}><div>{tickets.length?<div className="space-y-2">{tickets.slice(0,20).map(x=><div key={x.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-start gap-2"><span className="flex-1"><b className="block text-sm text-[#0b2447]">{x.subject}</b><span className="text-xs text-slate-500">{x.createdAt||'Unknown date'}</span></span><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{x.status.replace('_',' ')}</span></div><p className="mt-2 line-clamp-2 text-xs text-slate-500">{x.message||'No message'}</p></div>)}</div>:<Empty text="No support tickets found for this account."/>}</div></Panel>
     <Panel title="Available activity / audit" icon={<Shield size={18}/>}><div>{logs.length?<div className="space-y-2">{logs.slice(0,20).map(x=><div key={`${x.type}-${x.id}`} className="rounded-xl border border-slate-100 p-3"><div className="flex items-start gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${x.type==='audit'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{x.type}</span><span className="flex-1"><b className="block text-sm text-[#0b2447]">{x.summary}</b><span className="text-xs text-slate-500">{x.createdAt||'Unknown date'}</span></span></div></div>)}</div>:<Empty text="No matching activity or audit records were found in the available scope."/>}</div></Panel>
    </div>
   </>:<section className="flex min-h-[520px] items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center shadow-sm"><div className="max-w-md"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-[#e8f7f5] text-[#00a99d]"><FileSearch size={30}/></div><h2 className="mt-4 text-xl font-extrabold text-[#0b2447]">Select an account to investigate</h2><p className="mt-2 text-sm text-slate-500">Search by name, email or phone. The center is read-only and shows only data available to the current admin.</p><div className="mt-4 text-xs text-slate-400">Signed in as {profile?.email||'admin'}</div></div></section>}</main>
  </div>
 </div>
 }
