import { useMemo, useState } from 'react';
import { Activity, CheckCircle2, ChevronRight, Search, Shield, UserCog, UserX, Users, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { ALL_ROLES, assignableRoles, canEditTarget, FEATURE_LABELS, fetchUsersPage, filterBySearch, updateUserDisabled, updateUserFeatures, updateUserRole, type AdminUserRow, type FeatureAccess, type UserRole } from '../services/userManagementService';

export default function AdvancedUserOperationsPage() {
  const { profile } = useAuth(); const navigate = useNavigate();
  const [rows,setRows]=useState<AdminUserRow[]>([]); const [selected,setSelected]=useState<AdminUserRow|null>(null); const [query,setQuery]=useState(''); const [role,setRole]=useState<UserRole|'all'>('all'); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const r=await fetchUsersPage({roleFilter:role});setRows(r.rows);if(selected){const fresh=r.rows.find(x=>x.uid===selected.uid);if(fresh)setSelected(fresh)}}catch(e){console.error(e);setError('Could not load users. Check Firestore access and connection.')}finally{setLoading(false)}}
  const visible=useMemo(()=>filterBySearch(rows,query),[rows,query]); const actingRole=(profile?.role||'admin') as 'admin'|'superadmin'; const editable=selected?canEditTarget(actingRole,selected.role):false;
  async function saveRole(next:UserRole){if(!selected||!editable)return;setSaving(true);try{await updateUserRole(selected.uid,next);const updated={...selected,role:next};setSelected(updated);setRows(x=>x.map(r=>r.uid===updated.uid?updated:r))}catch(e){console.error(e);setError('Role update failed.')}finally{setSaving(false)}}
  async function saveDisabled(next:boolean){if(!selected||!editable)return;setSaving(true);try{await updateUserDisabled(selected.uid,next);const updated={...selected,disabled:next};setSelected(updated);setRows(x=>x.map(r=>r.uid===updated.uid?updated:r))}catch(e){console.error(e);setError('Account status update failed.')}finally{setSaving(false)}}
  async function toggleFeature(key:keyof FeatureAccess){if(!selected||!editable)return;setSaving(true);try{const features={...selected.features,[key]:!selected.features[key]};await updateUserFeatures(selected.uid,features);const updated={...selected,features};setSelected(updated);setRows(x=>x.map(r=>r.uid===updated.uid?updated:r))}catch(e){console.error(e);setError('Feature access update failed.')}finally{setSaving(false)}}
  const stats={loaded:rows.length,active:rows.filter(r=>!r.disabled).length,disabled:rows.filter(r=>r.disabled).length,privileged:rows.filter(r=>r.role==='admin'||r.role==='superadmin').length};
  return <div className="space-y-6 p-4 sm:p-6">
    <div className="rounded-3xl bg-gradient-to-r from-[#0b2447] via-[#155e9c] to-[#00a99d] p-6 text-white shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-white/80"><UserCog size={18}/> User Operations</div><h1 className="text-2xl font-extrabold sm:text-3xl">Advanced User Operations Center</h1><p className="mt-2 max-w-2xl text-sm text-white/75">Find an account, inspect its operational profile and apply only the account controls permitted for your role.</p></div><button onClick={load} disabled={loading} className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-[#0b2447] disabled:opacity-60">{loading?'Loading…':'Refresh users'}</button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([[Users,'Loaded',stats.loaded],[CheckCircle2,'Active',stats.active],[UserX,'Disabled',stats.disabled],[Shield,'Privileged',stats.privileged]] as const).map(([Icon,label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between text-sm text-slate-500"><span>{label}</span><Icon size={19}/></div><div className="mt-2 text-2xl font-extrabold text-[#0b2447]">{Number(value).toLocaleString()}</div></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_430px]">
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or phone…" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-[#00a99d]"/></div><select value={role} onChange={e=>{setRole(e.target.value as UserRole|'all');setRows([]);setSelected(null)}} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="all">All roles</option>{ALL_ROLES.map(r=><option key={r} value={r}>{r}</option>)}</select></div></div><div className="divide-y divide-slate-100">{visible.map(r=><button key={r.uid} onClick={()=>setSelected(r)} className={`flex w-full items-center gap-4 p-4 text-left transition hover:bg-slate-50 ${selected?.uid===r.uid?'bg-slate-50 ring-1 ring-inset ring-[#00a99d]':''}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 font-bold text-[#0b2447]">{r.name?.charAt(0)?.toUpperCase()||'U'}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-[#0b2447]">{r.name}</b><span className="block truncate text-xs text-slate-500">{r.email||r.phone||r.uid}</span></span><span className="hidden rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize sm:inline">{r.role}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${r.disabled?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{r.disabled?'Disabled':'Active'}</span><ChevronRight size={17} className="text-slate-400"/></button>)}{!loading&&!visible.length&&<div className="p-12 text-center text-sm text-slate-500">No users loaded. Click “Refresh users” or change the filter.</div>}</div></section>
      <aside className="rounded-2xl border border-slate-200 bg-white shadow-sm xl:sticky xl:top-6 xl:h-fit">{selected?<div><div className="border-b border-slate-100 p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#e8f7f5] text-lg font-extrabold text-[#00a99d]">{selected.name?.charAt(0)?.toUpperCase()||'U'}</span><div><h2 className="font-extrabold text-[#0b2447]">{selected.name}</h2><p className="text-xs text-slate-500">{selected.role}</p></div></div></div>{selected.disabled?<XCircle className="text-red-500"/>:<CheckCircle2 className="text-emerald-500"/>}</div><div className="mt-4 space-y-1 text-xs text-slate-500"><div><b>UID:</b> <span className="font-mono">{selected.uid}</span></div><div><b>Email:</b> {selected.email||'—'}</div><div><b>Phone:</b> {selected.phone||'—'}</div>{selected.dealerCode&&<div><b>Dealer code:</b> {selected.dealerCode}</div>}{selected.resellerCode&&<div><b>Reseller code:</b> {selected.resellerCode}</div>}</div></div>
        <div className="space-y-5 p-5"><div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-400">Account status</p><button disabled={!editable||saving} onClick={()=>saveDisabled(!selected.disabled)} className={`w-full rounded-xl px-4 py-3 text-sm font-bold ${selected.disabled?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'} disabled:cursor-not-allowed disabled:opacity-50`}>{selected.disabled?'Enable account':'Disable account'}</button></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-400">Role</p><select disabled={!editable||saving} value={selected.role} onChange={e=>saveRole(e.target.value as UserRole)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value={selected.role}>{selected.role}</option>{assignableRoles(actingRole).filter(r=>r!==selected.role).map(r=><option key={r} value={r}>{r}</option>)}</select></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-400">Feature access</p><div className="space-y-2">{(Object.keys(FEATURE_LABELS) as (keyof FeatureAccess)[]).map(key=><button key={key} disabled={!editable||saving} onClick={()=>toggleFeature(key)} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-3 py-2.5 text-left disabled:opacity-50"><span className="text-sm text-slate-700">{FEATURE_LABELS[key]}</span><span className={`h-5 w-9 rounded-full p-0.5 ${selected.features[key]?'bg-[#00a99d]':'bg-slate-300'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${selected.features[key]?'translate-x-4':''}`}/></span></button>)}</div></div><button onClick={()=>navigate('/users')} className="w-full rounded-xl border border-[#00a99d] px-4 py-2.5 text-sm font-bold text-[#008f85]">Open full User Management</button>{!editable&&<p className="text-xs text-amber-700">This account is at or above your permission level, so account controls are locked.</p>}</div></div>:<div className="p-10 text-center"><UserCog className="mx-auto text-slate-300" size={42}/><h2 className="mt-3 font-bold text-[#0b2447]">Select an account</h2><p className="mt-1 text-sm text-slate-500">Choose a user from the directory to inspect available controls.</p></div>}</aside>
    </div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="flex items-center gap-2 text-xs text-slate-500"><Activity size={15}/> Signed in as <strong>{profile?.role||'admin'}</strong>. Controls use the existing role-rank model and Firestore user records.</div>
  </div>;
}
