import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, CheckCircle2, RefreshCw, Star, TrendingUp, Users } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { getDashboard, setErrorResolved, subscribeActivityLog, subscribeAuditLog, subscribeErrorLog, type AnalyticsDashboard, type LogEntry } from '../services/analyticsService';

function Card({ label, value, icon: Icon, hint }: { label: string; value: number | string; icon: typeof Users; hint?: string }) {
  return <div className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-card)] p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-2xl font-extrabold">{value}</p><p className="mt-1 text-sm text-[var(--color-ink-soft)]">{label}</p></div><div className="rounded-xl bg-[var(--color-primary)]/10 p-3 text-[var(--color-primary)]"><Icon size={20}/></div></div>{hint && <p className="mt-3 text-xs text-[var(--color-ink-soft)]">{hint}</p>}</div>;
}

function Overview({ data }: { data: AnalyticsDashboard }) {
  const max = Math.max(1, ...data.trend.map(x => x.count));
  const roleRows = Object.entries(data.users.byRole).filter(([,v]) => v > 0).sort((a,b) => b[1]-a[1]);
  const totalRoles = Math.max(1, roleRows.reduce((a,[,v]) => a+v, 0));
  const top = useMemo(() => data.modules.slice().sort((a,b) => b.total-a.total), [data.modules]);

  return <div className="mt-6 space-y-6">
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
      <Card label="Registered users" value={data.users.total} icon={Users} hint={`${data.users.verified} verified`}/>
      <Card label="Marketplace activity" value={data.modules.reduce((a,m)=>a+m.total,0)} icon={Activity} hint="Listings, properties, services, community"/>
      <Card label="Open reports" value={data.reports.open} icon={AlertTriangle} hint={`${data.reports.total} total reports`}/>
      <Card label="Average rating" value={data.reviews.avg ? data.reviews.avg.toFixed(1) : '—'} icon={Star} hint={`${data.reviews.count} reviews`}/>
    </div>

    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]">
      <section className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-card)] p-5">
        <div className="flex items-center justify-between"><div><h2 className="font-bold">Platform Activity</h2><p className="mt-1 text-xs text-[var(--color-ink-soft)]">New marketplace/community records · last 7 days</p></div><TrendingUp size={18} className="text-[var(--color-primary)]"/></div>
        <div className="mt-6 flex h-48 items-end gap-2 sm:gap-4">{data.trend.map((t,i)=><div key={`${t.label}-${i}`} className="flex h-full flex-1 flex-col items-center justify-end gap-1"><span className="text-[10px] font-semibold">{t.count}</span><div className="w-full max-w-12 rounded-t-lg bg-[var(--color-primary)]/70 transition-all" style={{height:`${Math.max(6,(t.count/max)*130)}px`}}/><span className="text-[10px] text-[var(--color-ink-soft)]">{t.label}</span></div>)}</div>
      </section>
      <section className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-card)] p-5"><h2 className="font-bold">User Distribution</h2><div className="mt-5 space-y-3">{roleRows.length ? roleRows.map(([role,count])=><div key={role}><div className="flex justify-between text-xs"><span className="capitalize">{role}</span><b>{count}</b></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[var(--color-secondary)]" style={{width:`${(count/totalRoles)*100}%`}}/></div></div>) : <p className="text-sm text-[var(--color-ink-soft)]">No role data.</p>}</div></section>
    </div>

    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-card)] p-5"><h2 className="font-bold">Service / Module Performance</h2><div className="mt-4 space-y-3">{top.map(m=><div key={m.key} className="flex items-center gap-3"><span className="w-7 text-lg">{m.icon}</span><span className="min-w-0 flex-1 truncate text-sm font-semibold">{m.label}</span><span className="text-xs text-[var(--color-ink-soft)]">{m.active} active</span><b className="w-14 text-right text-sm">{m.total}</b></div>)}</div></section>
      <section className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-card)] p-5"><h2 className="font-bold">Report Breakdown</h2><div className="mt-4 space-y-3">{data.reports.byKind.map(r=><div key={r.kind} className="flex items-center gap-3"><span className="min-w-0 flex-1 text-sm font-semibold">{r.label}</span><span className="text-xs text-[var(--color-ink-soft)]">{r.total} total</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${r.open ? 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]' : 'bg-[var(--color-success)]/10 text-[var(--color-success)]'}`}>{r.open} open</span></div>)}</div></section>
    </div>

    {data.topCategories.length > 0 && <section className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-card)] p-5"><h2 className="font-bold">Top Active Listing Categories</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{data.topCategories.map((c,i)=><div key={c.category} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-[var(--color-ink-soft)]">#{i+1}</p><p className="mt-1 truncate text-sm font-bold">{c.category}</p><p className="mt-1 text-xl font-extrabold">{c.count}</p></div>)}</div></section>}
  </div>;
}

function LogRow({ entry, resolvable, onResolve }: { entry: LogEntry; resolvable?: boolean; onResolve?: (v:boolean)=>void }) { const {id,createdAt,...rest}=entry; return <div className="rounded-xl border border-[var(--color-line)] bg-[var(--color-card)] p-4"><div className="flex flex-wrap justify-between gap-2"><b>{String(rest.action ?? rest.context ?? id)}</b><span className="text-xs text-[var(--color-ink-soft)]">{String(createdAt ?? '')}</span></div>{'message' in rest&&<p className="mt-1 text-sm text-[var(--color-danger)]">{String(rest.message)}</p>}<pre className="mt-2 overflow-x-auto whitespace-pre-wrap break-all text-xs text-[var(--color-ink-soft)]">{JSON.stringify(rest,null,1)}</pre>{resolvable&&<button onClick={()=>onResolve?.(!rest.resolved)} className={`mt-2 rounded-lg px-3 py-1 text-xs font-semibold ${rest.resolved?'border border-[var(--color-line)]':'bg-[var(--color-success)] text-white'}`}>{rest.resolved?'Mark unresolved':'Mark resolved'}</button>}</div> }

function ActivityLogs() { const [tab,setTab]=useState<'activity'|'errors'|'audit'>('activity'); const [activity,setActivity]=useState<LogEntry[]>([]),[errors,setErrors]=useState<LogEntry[]>([]),[audit,setAudit]=useState<LogEntry[]>([]),[error,setError]=useState<string|null>(null); useEffect(()=>subscribeActivityLog(setActivity,e=>setError(e.message)),[]); useEffect(()=>subscribeErrorLog(setErrors,e=>setError(e.message)),[]); useEffect(()=>subscribeAuditLog(setAudit,e=>setError(e.message)),[]); const list=tab==='activity'?activity:tab==='errors'?errors:audit; return <div className="mt-6"><div className="flex gap-2">{(['activity','errors','audit'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-full px-4 py-1.5 text-sm font-semibold ${tab===t?'bg-[var(--color-primary)] text-white':'border border-[var(--color-line)]'}`}>{t==='activity'?'📈 Activity':t==='errors'?'⚠️ Errors':'🔒 Audit'}</button>)}</div>{error&&<div className="mt-4 rounded-lg border border-[var(--color-danger)]/30 bg-[var(--color-danger)]/5 px-4 py-3 text-sm text-[var(--color-danger)]">{error}</div>}<div className="mt-4 space-y-2">{list.length?list.map(e=><LogRow key={e.id} entry={e} resolvable={tab==='errors'} onResolve={tab==='errors'?v=>setErrorResolved(e.id,v):undefined}/>):<p className="text-sm text-[var(--color-ink-soft)]">Nothing here.</p>}</div></div> }

export default function AnalyticsPage() { const {profile}=useAuth(); const superadmin=profile?.role==='superadmin'; const [tab,setTab]=useState<'overview'|'logs'>('overview'); const [data,setData]=useState<AnalyticsDashboard|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const load=()=>{setLoading(true);setError(null);getDashboard().then(setData).catch(e=>setError(e.message||'Could not load analytics.')).finally(()=>setLoading(false));}; useEffect(load,[]); return <div><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Business Intelligence</h1><p className="mt-1 text-sm text-[var(--color-ink-soft)]">Live platform performance, user distribution and service activity.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-[var(--color-line)] bg-white px-3 py-2 text-xs font-semibold"><RefreshCw size={14}/> Refresh</button></div>{superadmin&&<div className="mt-4 flex gap-2"><button onClick={()=>setTab('overview')} className={`rounded-full px-4 py-1.5 text-sm font-semibold ${tab==='overview'?'bg-[var(--color-primary)] text-white':'border border-[var(--color-line)]'}`}>📊 Overview</button><button onClick={()=>setTab('logs')} className={`rounded-full px-4 py-1.5 text-sm font-semibold ${tab==='logs'?'bg-[var(--color-primary)] text-white':'border border-[var(--color-line)]'}`}>🗂️ Activity Logs</button></div>}{error&&<div className="mt-4 rounded-xl border border-[var(--color-danger)]/30 bg-[var(--color-danger)]/5 px-4 py-3 text-sm text-[var(--color-danger)]">{error}</div>}{tab==='logs'&&superadmin?<ActivityLogs/>:loading?<p className="mt-6 text-sm text-[var(--color-ink-soft)]">Loading analytics…</p>:data?<Overview data={data}/>:null}</div> }
