import { useEffect, useMemo, useState } from 'react';
import { BellRing, Megaphone, RefreshCw, Send, Users } from 'lucide-react';
import { ANNOUNCEMENT_AUDIENCES, sendAnnouncement, subscribeAnnouncements, type AnnouncementAudience, type AnnouncementLogEntry } from '../services/announcementService';

const labels = Object.fromEntries(ANNOUNCEMENT_AUDIENCES.map(a => [a.key, a.label]));
export default function CommunicationsCenterPage() {
  const [title,setTitle]=useState(''); const [body,setBody]=useState(''); const [audience,setAudience]=useState<AnnouncementAudience>('all'); const [history,setHistory]=useState<AnnouncementLogEntry[]>([]); const [sending,setSending]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState('');
  useEffect(()=>subscribeAnnouncements(setHistory, e=>setError(e.message)),[]);
  const stats=useMemo(()=>({sent:history.reduce((n,x)=>n+(x.sentCount||0),0),matched:history.reduce((n,x)=>n+(x.matchedCount||0),0),broadcasts:history.length}),[history]);
  async function send(){if(!title.trim()||!body.trim())return;setSending(true);setError('');setResult('');try{const r=await sendAnnouncement({title:title.trim(),body:body.trim(),audience});setResult(`Sent to ${r.sentCount} of ${r.matchedCount} matching accounts.`);setTitle('');setBody('');}catch(e){setError((e as Error).message||'Could not send campaign.');}finally{setSending(false);}}
  return <div className="space-y-6 p-4 sm:p-6"><div className="rounded-3xl bg-gradient-to-r from-[#00a99d] to-[#1a73e8] p-6 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold opacity-90"><Megaphone size={18}/> Customer Communications</div><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Campaign Center</h1><p className="mt-2 text-sm opacity-90">Create targeted push campaigns and monitor delivery history.</p></div><a href="/notifications" className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#0b2447]">Delivery Center</a></div></div>
  <div className="grid gap-4 sm:grid-cols-3"><Stat icon={BellRing} label="Broadcasts" value={stats.broadcasts}/><Stat icon={Users} label="Matched recipients" value={stats.matched}/><Stat icon={Send} label="Notifications sent" value={stats.sent}/></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-[#0b2447]">Create campaign</h2><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_240px]"><div className="space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Campaign title" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#00a99d]"/><textarea value={body} onChange={e=>setBody(e.target.value)} rows={5} placeholder="Write your notification message…" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#00a99d]"/></div><div className="space-y-3"><label className="block text-xs font-semibold text-slate-500">Target audience<select value={audience} onChange={e=>setAudience(e.target.value as AnnouncementAudience)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{ANNOUNCEMENT_AUDIENCES.map(a=><option key={a.key} value={a.key}>{a.label}</option>)}</select></label><div className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">Delivery is handled by the existing announcement backend. This center does not fake delivery counts.</div><button onClick={send} disabled={sending||!title.trim()||!body.trim()} className="w-full rounded-xl bg-[#00a99d] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{sending?'Sending…':'Send campaign'}</button></div></div>{result&&<p className="mt-3 text-sm text-emerald-600">{result}</p>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div>
  <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold text-[#0b2447]">Communication history</h2><p className="mt-1 text-sm text-slate-500">Live history from the announcements collection.</p></div><button onClick={()=>location.reload()} className="rounded-lg border border-slate-200 p-2"><RefreshCw size={16}/></button></div><div className="divide-y divide-slate-100">{history.length?history.map(a=><div key={a.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-[#0b2447]">{a.title}</p><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold uppercase">{labels[a.audience]||a.audience}</span></div><p className="mt-1 text-sm text-slate-600">{a.body}</p><p className="mt-2 text-xs text-slate-400">{a.createdAt||'—'} · {a.sentByName||'unknown'} · delivered {a.sentCount}/{a.matchedCount}</p></div>):<div className="p-10 text-center text-sm text-slate-500">No communication history yet.</div>}</div></div></div>;
}
function Stat({icon:Icon,label,value}:{icon:typeof BellRing;label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between text-sm text-slate-500"><span>{label}</span><Icon size={18}/></div><p className="mt-2 text-2xl font-bold text-[#0b2447]">{value.toLocaleString()}</p></div>}
