import { useEffect, useMemo, useState } from 'react';
import { AlertOctagon, AlertTriangle, CheckCircle2, Clock3, ExternalLink, RefreshCw, ShieldCheck, TrendingDown, WalletCards, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { subscribeTransactions, type Transaction } from '../services/transactionService';

export default function FinancialRiskControlsPage() {
  const navigate=useNavigate(); const [txs,setTxs]=useState<Transaction[]>([]); const [error,setError]=useState(''); const [refresh,setRefresh]=useState(0);
  useEffect(()=>{setError('');return subscribeTransactions(setTxs,e=>setError(e.message||'Unable to load transaction risk data.'));},[refresh]);
  const s=useMemo(()=>{const value=(a:Transaction[])=>a.reduce((n,t)=>n+(Number(t.total)||0),0);const pending=txs.filter(t=>t.status==='pending'&&!t.rejected);const processing=txs.filter(t=>t.status==='processing'&&!t.rejected);const rejected=txs.filter(t=>t.rejected);const high=txs.filter(t=>(Number(t.total)||0)>=10000&&!t.rejected);const unapproved=txs.filter(t=>!t.approved&&!t.rejected);const completed=txs.filter(t=>t.status==='completed'&&!t.rejected);return {value:value(txs),pending,processing,rejected,high,unapproved,completed,completedValue:value(completed),pendingValue:value(pending),rejectedValue:value(rejected)}},[txs]);
  const alerts=[{label:'High-value transactions (≥ MYR 10,000)',count:s.high.length,critical:s.high.length>0,icon:AlertOctagon},{label:'Transactions awaiting approval',count:s.pending.length,critical:s.pending.length>0,icon:Clock3},{label:'Rejected transactions',count:s.rejected.length,critical:s.rejected.length>0,icon:XCircle},{label:'Unapproved transaction records',count:s.unapproved.length,critical:s.unapproved.length>0,icon:AlertTriangle}];
  return <div className="space-y-6">
    <div className="rounded-3xl bg-gradient-to-r from-[#0b2447] via-[#155e9c] to-[#00a99d] p-6 text-white shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-white/80"><ShieldCheck size={18}/> Financial Risk & Controls</div><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">Financial Risk Control Center</h1><p className="mt-2 max-w-2xl text-sm text-white/75">A live operational view of transaction exposure, exceptions and control signals. This workspace surfaces risk; it does not make automatic fraud decisions.</p></div><button onClick={()=>setRefresh(x=>x+1)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-[#0b2447]"><RefreshCw size={16}/> Refresh</button></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{([[WalletCards,'Gross transaction value',`MYR ${s.value.toFixed(2)}`],[TrendingDown,'Rejected value',`MYR ${s.rejectedValue.toFixed(2)}`],[Clock3,'Pending value',`MYR ${s.pendingValue.toFixed(2)}`],[CheckCircle2,'Completed value',`MYR ${s.completedValue.toFixed(2)}`],[AlertOctagon,'High-value',s.high.length],[ShieldCheck,'Completed count',s.completed.length]] as const).map(([I,l,v])=><div key={String(l)} className="rounded-2xl border border-[var(--color-line)] bg-white p-4 shadow-sm"><div className="flex justify-between text-xs font-semibold text-[var(--color-ink-soft)]"><span>{l}</span><I size={17} className="text-[var(--color-primary)]"/></div><p className="mt-3 text-xl font-extrabold tracking-tight">{v}</p></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <section className="rounded-2xl border border-[var(--color-line)] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-[#0b2447]">Control signals</h2><p className="mt-1 text-xs text-[var(--color-ink-soft)]">Prioritize exceptions requiring operator review.</p></div><AlertTriangle size={20} className="text-[var(--color-warning)]"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{alerts.map(({label,count,critical:bad,icon:I})=><div key={label} className={`rounded-2xl border p-4 ${bad?'border-red-200 bg-red-50/50':'border-emerald-200 bg-emerald-50/50'}`}><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-[#0b2447]">{label}</p><p className={`mt-2 text-2xl font-extrabold ${bad?'text-red-700':'text-emerald-700'}`}>{count}</p></div><I size={20} className={bad?'text-red-600':'text-emerald-600'}/></div><p className="mt-2 text-xs text-slate-500">{bad?'Requires review':'No current signal'}</p></div>)}</div></section>
      <section className="rounded-2xl border border-[var(--color-line)] bg-white p-5 shadow-sm"><h2 className="font-extrabold text-[#0b2447]">Control actions</h2><div className="mt-4 space-y-2"><button onClick={()=>navigate('/transactions')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-left text-sm font-bold hover:border-[var(--color-primary)]"><span>Review transaction queue</span><ExternalLink size={16}/></button><button onClick={()=>navigate('/fraud-risk')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-left text-sm font-bold hover:border-[var(--color-primary)]"><span>Open fraud risk workspace</span><ExternalLink size={16}/></button><button onClick={()=>navigate('/wallet-settlement')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-left text-sm font-bold hover:border-[var(--color-primary)]"><span>Review wallet settlement</span><ExternalLink size={16}/></button><button onClick={()=>navigate('/config/payments')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-left text-sm font-bold hover:border-[var(--color-primary)]"><span>Open payment controls</span><ExternalLink size={16}/></button><button onClick={()=>navigate('/audit')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-left text-sm font-bold hover:border-[var(--color-primary)]"><span>Inspect audit records</span><ExternalLink size={16}/></button></div></section>
    </div>
    <section className="rounded-2xl border border-[var(--color-line)] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-[#0b2447]">Latest financial activity</h2><p className="mt-1 text-xs text-[var(--color-ink-soft)]">Live records from the existing transaction collection.</p></div><WalletCards size={19} className="text-[var(--color-primary)]"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-slate-500"><th className="px-3 py-3">Service</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Value</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Approval</th><th className="px-3 py-3">Created</th></tr></thead><tbody>{txs.slice(0,12).map(t=><tr key={t.id} className="border-b border-slate-50"><td className="px-3 py-3 font-semibold">{t.service||'Transaction'}</td><td className="px-3 py-3">{t.customerPhone||'—'}</td><td className="px-3 py-3 font-bold">MYR {(Number(t.total)||0).toFixed(2)}</td><td className="px-3 py-3 capitalize">{t.rejected?'rejected':t.status}</td><td className="px-3 py-3">{t.approved?'Approved':'Pending'}</td><td className="px-3 py-3 text-slate-500">{t.createdAt||'—'}</td></tr>)}{!txs.length&&<tr><td colSpan={6} className="px-3 py-10 text-center text-slate-500">No transaction records available.</td></tr>}</tbody></table></div></section>
    <div className="flex items-start gap-2 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-xs text-blue-800"><CheckCircle2 size={16} className="mt-0.5 shrink-0"/><span><b>Data boundary:</b> high-value, pending, rejected and approval signals are calculated from currently available transaction records. No unsupported balance, velocity, AML or automatic fraud score is invented.</span></div>
  </div>;
}
