import { useEffect, useState } from 'react';
import { Globe2, Layers3, Megaphone, Plus, Save, Smartphone, Trash2, Users } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import * as service from '../services/platformControlService';

const SERVICE_KEYS = ['recharge','internet','billpayment','mobilebanking','remittance','offerpacks','entertainment','rechargePin','bus','train','flight','topup','history','support','myAccount','profile','walletTransfer','myDocuments','salary','kyc'];
function csv(v: string[] | undefined){ return (v||[]).join(', '); }
function parseCsv(v: string){ return v.split(',').map(x=>x.trim()).filter(Boolean); }

export default function PlatformControlCenterPage(){
  const { profile } = useAuth();
  const [tab,setTab]=useState<'features'|'countries'|'operators'|'webviews'|'ads'>('features');
  const [data,setData]=useState<service.CatalogAdmin|null>(null);
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [feature,setFeature]=useState<any>({key:'',name:'',description:'',icon:'✨',kind:'webview',webviewKey:'',serviceKey:'recharge',screenKey:'moreFeatures',enabled:true,home:true,roles:[],countries:[],sortOrder:999});
  const [country,setCountry]=useState<any>({code:'',name:'',flag:'🌍',dial:'',currency:'MYR',enabled:true,sortOrder:999});
  const [operator,setOperator]=useState<any>({id:'',name:'',country:'MY',logo:'',enabled:true,recharge:true,internet:true,offerPacks:true,entertainment:true,sortOrder:999});
  const [target,setTarget]=useState<any>(null);
  const [ads,setAds]=useState<Record<string,boolean>>({});

  async function load(){ setBusy(true); setError(''); try { const x=await service.listCatalog(); setData(x); setAds(x.ads||{}); } catch(e:any){ setError(e?.message||'Could not load platform controls.'); } finally{setBusy(false);} }
  useEffect(()=>{ if(profile?.role==='superadmin') load(); },[profile?.role]);
  if(profile?.role!=='superadmin') return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">Only Superadmin can manage platform controls.</div>;
  async function run(fn:()=>Promise<any>){ setBusy(true); setError(''); try{ await fn(); await load(); }catch(e:any){setError(e?.message||'Operation failed.');}finally{setBusy(false);} }

  return <div className="mx-auto max-w-[1500px] space-y-5 pb-10">
    <div className="rounded-3xl bg-gradient-to-r from-[#0b2447] via-[#155e9c] to-[#00a99d] p-6 text-white shadow-lg"><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/60">Superadmin</p><h1 className="mt-1 text-2xl font-extrabold md:text-3xl">Platform Control Center</h1><p className="mt-2 max-w-3xl text-sm text-white/75">Control tiles, features, countries, operators, WebView targeting and Google Ads from one server-owned panel. Changes are live and do not require an app build.</p></div>
    <div className="flex flex-wrap gap-2">{[['features','Features',Layers3],['countries','Countries',Globe2],['operators','Operators',Smartphone],['webviews','WebViews',Users],['ads','Google Ads',Megaphone]].map(([k,l,I]:any)=><button key={k} onClick={()=>setTab(k)} className={tab===k?'rounded-xl bg-[#0b2447] px-4 py-2 text-sm font-bold text-white':'rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700'}><I size={16} className="mr-2 inline"/>{l}</button>)}</div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}

    {tab==='features' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <h2 className="font-extrabold text-[#0b2447]">Dynamic Features & Grid Tiles</h2><p className="mt-1 text-xs text-slate-500">Create a new tile targeting an existing service, supported screen, or a Superadmin WebView. Built-in service code remains protected.</p>
      <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">
        {(['key','name','description','icon','sortOrder'] as const).map(k=><input key={k} value={feature[k]??''} onChange={e=>setFeature({...feature,[k]:k==='sortOrder'?Number(e.target.value):e.target.value})} placeholder={k} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"/>)}
        <select value={feature.kind} onChange={e=>setFeature({...feature,kind:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="webview">WebView</option><option value="service">Existing Service</option><option value="screen">Existing Screen</option></select>
        {feature.kind==='webview' && <input value={feature.webviewKey} onChange={e=>setFeature({...feature,webviewKey:e.target.value})} placeholder="WebView key" className="rounded-xl border border-slate-200 px-3 py-2 text-sm"/>}
        {feature.kind==='service' && <select value={feature.serviceKey} onChange={e=>setFeature({...feature,serviceKey:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">{SERVICE_KEYS.map(k=><option key={k}>{k}</option>)}</select>}
        {feature.kind==='screen' && <select value={feature.screenKey} onChange={e=>setFeature({...feature,screenKey:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">{['moreFeatures','history','topup','profile','myAccount','transferPoints','verifyIdentity','support'].map(k=><option key={k}>{k}</option>)}</select>}
        <input value={csv(feature.roles)} onChange={e=>setFeature({...feature,roles:parseCsv(e.target.value)})} placeholder="Roles: customer,dealer" className="rounded-xl border border-slate-200 px-3 py-2 text-sm md:col-span-2"/>
        <input value={csv(feature.countries)} onChange={e=>setFeature({...feature,countries:parseCsv(e.target.value).map(x=>x.toUpperCase())})} placeholder="Countries: MY,BD,IN" className="rounded-xl border border-slate-200 px-3 py-2 text-sm md:col-span-2"/>
      </div>
      <button disabled={busy} onClick={()=>run(()=>service.saveFeature(feature))} className="mt-3 rounded-xl bg-[#00a99d] px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Save size={15} className="mr-2 inline"/>Save Feature</button>
      <div className="mt-6 divide-y">{data?.features.map(f=><div key={f.id} className="flex flex-wrap items-center gap-3 py-3"><span className="text-xl">{f.icon||'✨'}</span><div className="min-w-[180px] flex-1"><b>{f.name}</b><small className="ml-2 text-slate-400">{f.key}</small><div className="text-xs text-slate-500">{f.kind} · {f.roles?.length?csv(f.roles):'all roles'} · {f.countries?.length?csv(f.countries):'all countries'}</div></div><button onClick={()=>run(()=>service.deleteFeature(f.id))} className="rounded-lg border border-red-200 px-3 py-2 text-red-600"><Trash2 size={15}/></button></div>)}</div>
    </section>}

    {tab==='countries' && <CatalogSection title="Country Catalogue" icon={<Globe2 size={18}/>} rows={data?.countries||[]} fields={country} setFields={setCountry} onSave={()=>run(()=>service.saveCountry(country))} onDelete={id=>run(()=>service.deleteCountry(id))} labels={['code','name','flag','dial','currency','sortOrder']}/>}
    {tab==='operators' && <CatalogSection title="Operator Catalogue" icon={<Smartphone size={18}/>} rows={data?.operators||[]} fields={operator} setFields={setOperator} onSave={()=>run(()=>service.saveOperator(operator))} onDelete={id=>run(()=>service.deleteOperator(id))} labels={['id','name','country','logo','sortOrder']}/>}
    {tab==='webviews' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-extrabold text-[#0b2447]">WebView Access Targeting</h2><p className="mt-1 text-xs text-slate-500">Leave a list empty for unrestricted access. Otherwise the user must match every non-empty targeting dimension.</p><div className="mt-4 space-y-2">{(data?.webviews||[]).map((w:any)=><div key={w.key} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-3"><span className="text-lg">{w.icon||'🌐'}</span><div className="min-w-0 flex-1"><b>{w.name||w.title}</b><div className="truncate text-xs text-slate-500">{w.key} · {w.url}</div></div><button onClick={()=>setTarget({key:w.key,roles:w.roles||[],countries:w.countries||[],users:w.users||[]})} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Target</button></div>{target?.key===w.key&&<div className="mt-3 grid gap-2 md:grid-cols-3"><input value={csv(target.roles)} onChange={e=>setTarget({...target,roles:parseCsv(e.target.value)})} placeholder="Roles" className="rounded-lg border px-3 py-2 text-sm"/><input value={csv(target.countries)} onChange={e=>setTarget({...target,countries:parseCsv(e.target.value).map((x:string)=>x.toUpperCase())})} placeholder="Countries" className="rounded-lg border px-3 py-2 text-sm"/><input value={csv(target.users)} onChange={e=>setTarget({...target,users:parseCsv(e.target.value)})} placeholder="UIDs" className="rounded-lg border px-3 py-2 text-sm"/><button onClick={()=>run(()=>service.targetWebview(target))} className="rounded-lg bg-[#00a99d] px-3 py-2 text-sm font-bold text-white md:col-span-3">Save Targeting</button></div>}</div>)}</div></section>}
    {tab==='ads' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-extrabold text-[#0b2447]">Google Ads Controls</h2><p className="mt-1 text-xs text-slate-500">These controls govern the mobile ad settings. MySheba Direct Ads remain separately managed.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{['adsEnabled','bannerAdsEnabled','nativeAdsEnabled','interstitialAdsEnabled','directAdsEnabled'].map(k=><label key={k} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span className="text-sm font-bold">{k}</span><input type="checkbox" checked={ads[k]!==false} onChange={e=>setAds({...ads,[k]:e.target.checked})}/></label>)}</div><button disabled={busy} onClick={()=>run(()=>service.updateAds(ads))} className="mt-4 rounded-xl bg-[#00a99d] px-4 py-2 text-sm font-bold text-white"><Save size={15} className="mr-2 inline"/>Save Google Ads Controls</button></section>}
    {busy && <div className="text-xs text-slate-500">Saving/loading…</div>}
  </div>;
}

function CatalogSection({title,icon,rows,fields,setFields,onSave,onDelete,labels}:{title:string;icon:any;rows:any[];fields:any;setFields:(x:any)=>void;onSave:()=>void;onDelete:(id:string)=>void;labels:string[]}){
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-extrabold text-[#0b2447]">{icon}{title}</h2><div className="mt-4 grid gap-2 md:grid-cols-3 lg:grid-cols-6">{labels.map(k=><input key={k} value={fields[k]??''} onChange={e=>setFields({...fields,[k]:k==='sortOrder'?Number(e.target.value):e.target.value})} placeholder={k} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"/>)}</div><button onClick={onSave} className="mt-3 rounded-xl bg-[#00a99d] px-4 py-2 text-sm font-bold text-white"><Plus size={15} className="mr-2 inline"/>Save</button><div className="mt-5 divide-y">{rows.map((r:any)=><div key={r.id} className="flex items-center gap-3 py-3"><span className="min-w-0 flex-1"><b>{r.name||r.code}</b><small className="ml-2 text-slate-400">{r.code||r.id}{r.country ? ' · '+r.country : ''}</small></span><button onClick={()=>onDelete(r.id||r.code)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 size={15}/></button></div>)}</div></section>;
}
