import { useNavigate } from 'react-router-dom';
import { ShieldCheck, Settings2, Users, SlidersHorizontal, CreditCard, Layers, Tags, Percent, Megaphone, Lock, Smartphone, FileText, Activity, ArrowRight } from 'lucide-react';

const sections = [
  { title:'Access & Security', icon:ShieldCheck, tone:'bg-blue-50 text-blue-700', items:[['Role & Permissions','/role-permissions','Review the live role hierarchy and tool permission matrix.',Users],['Tool Access','/tool-access','Manage staff access to administrative tools.',SlidersHorizontal],['Security Center','/security','Review device sessions and account security controls.',Lock],['Device Sessions','/devices','Inspect active administrative device sessions.',Smartphone]] },
  { title:'Money & Payments', icon:CreditCard, tone:'bg-purple-50 text-purple-700', items:[['Rates & Pricing','/config/rates','Manage exchange rates and service pricing.',Percent],['Pricing','/config/pricing','Review customer and service pricing.',Percent],['Payment Settings','/config/payments','Configure payment and collection settings.',CreditCard],['Salary Settings','/config/salary','Review salary and commission configuration.',FileText]] },
  { title:'Governance & Monitoring', icon:Activity, tone:'bg-amber-50 text-amber-700', items:[['Audit & Compliance','/audit','Inspect administrative audit and activity records.',FileText],['System Health','/system-health','Review available platform health signals.',Activity],['Financial Risk','/financial-risk','Review financial exception and risk signals.',ShieldCheck],['Reports & Analytics','/reports','Review operational reports and analytics.',Activity]] },
  { title:'Platform Configuration', icon:Settings2, tone:'bg-emerald-50 text-emerald-700', items:[['Feature Access','/feature-access','Control which modules each customer can use.',SlidersHorizontal],['Banners','/config/banners','Manage the banners shown in the mobile app.',Megaphone],['Categories','/config/categories','Maintain the service category list.',Tags],['Module Subscriptions','/config/modules','Review module plans and their pricing.',Layers]] },
] as const;

export default function SystemGovernanceCenterPage(){const navigate=useNavigate();return <div className="mx-auto max-w-[1450px] space-y-6 pb-10">
  <header className="rounded-3xl bg-gradient-to-r from-[#0b2447] via-[#155e9c] to-[#00a99d] p-6 text-white shadow-lg md:p-8"><div className="flex items-start gap-4"><span className="rounded-2xl bg-white/15 p-3"><ShieldCheck size={28}/></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/60">Superadmin Governance</p><h1 className="mt-1 text-2xl font-extrabold md:text-3xl">System Configuration & Governance Center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-white/75">One governance workspace for access, security, platform configuration, financial controls and operational oversight. Existing permission boundaries remain enforced.</p></div></div></header>
  <div className="grid gap-5 xl:grid-cols-2">{sections.map(({title,icon:SectionIcon,tone,items})=><section key={title} className="rounded-2xl border border-[var(--color-line)] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className={`rounded-xl p-2.5 ${tone}`}><SectionIcon size={20}/></span><div><h2 className="font-extrabold text-[#0b2447]">{title}</h2><p className="text-xs text-[var(--color-ink-soft)]">{items.length} control areas</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map(([label,path,description,Icon])=><button key={path} onClick={()=>navigate(path)} className="group flex items-center gap-3 rounded-xl border border-slate-200 p-3.5 text-left transition hover:-translate-y-0.5 hover:border-[#00a99d] hover:shadow-sm"><span className="rounded-lg bg-slate-50 p-2 text-[#00a99d]"><Icon size={17}/></span><span className="min-w-0 flex-1"><b className="block text-sm text-[#0b2447]">{label}</b><small className="mt-1 block leading-4 text-slate-500">{description}</small></span><ArrowRight size={15} className="shrink-0 text-slate-300 transition group-hover:text-[#00a99d]"/></button>)}</div></section>)}</div>
  <section className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><div className="flex items-start gap-3"><ShieldCheck size={19} className="mt-0.5 shrink-0 text-blue-700"/><div><h2 className="font-bold text-blue-900">Governance boundary</h2><p className="mt-1 text-sm leading-6 text-blue-800">This center organizes access to existing controls; it does not create a second permission engine, silently change security settings, or bypass backend authorization. Use the linked control page for each actual change.</p></div></div></section>
</div>}
